Repository freqtrade/freqtrade, pull requests merged in 2020-02, with the labels that each got.

#2779 Stoploss on exchange for Kraken
  docs/configuration.md
  docs/exchanges.md
  docs/stoploss.md
  freqtrade/exchange/binance.py
  freqtrade/exchange/exchange.py
  freqtrade/exchange/kraken.py
  freqtrade/freqtradebot.py
  tests/exchange/test_binance.py
  tests/exchange/test_exchange.py
  tests/exchange/test_kraken.py
  tests/test_freqtradebot.py
  tests/test_integration.py
Labels: Enhancement

#2870 Add considerations for dry-run
  docs/configuration.md
Labels: Documentation

#2900 Break the old binary file so users are forced to reinstall
  bin/freqtrade
Labels: Tech debt

#2888 Added filter options to "hyperopt-list" in order to easier find epochs.
  docs/utils.md
  freqtrade/commands/arguments.py
  freqtrade/commands/cli_options.py
  freqtrade/commands/hyperopt_commands.py
  freqtrade/configuration/configuration.py
  tests/commands/test_commands.py
Labels: hyperopt

#2886 Docker docs
  docker-compose.yml
  docs/docker.md
Labels: docker

#2905 Adding --min-trades and --max-trades for hyperopt-list
  docs/utils.md
  freqtrade/commands/arguments.py
  freqtrade/commands/cli_options.py
  freqtrade/commands/hyperopt_commands.py
  freqtrade/configuration/configuration.py
  tests/commands/test_commands.py
Labels: don't merge

#2915 fix configuration table
  docs/configuration.md
Labels: Documentation, don't merge

#2887 Wide RPC notifications fixes
  docs/configuration.md
  docs/telegram-usage.md
  docs/webhook-config.md
  freqtrade/constants.py
  freqtrade/freqtradebot.py
  freqtrade/rpc/rpc.py
  freqtrade/rpc/telegram.py
  freqtrade/rpc/webhook.py
  tests/rpc/test_rpc.py
  tests/rpc/test_rpc_telegram.py
  tests/rpc/test_rpc_webhook.py
  tests/test_freqtradebot.py
Labels: Enhancement, RPC

#2925 Fix edge documentation rendering
  docs/edge.md
Labels: Documentation

#2719 Introduce Data handler
  config_full.json.example
  docs/configuration.md
  docs/data-download.md
  freqtrade/commands/__init__.py
  freqtrade/commands/arguments.py
  freqtrade/commands/cli_options.py
  freqtrade/commands/data_commands.py
  freqtrade/configuration/configuration.py
  freqtrade/constants.py
  freqtrade/data/converter.py
  freqtrade/data/history/__init__.py
  freqtrade/data/history/history_utils.py
  freqtrade/data/history/idatahandler.py
  freqtrade/data/history/jsondatahandler.py
  freqtrade/edge/edge_positioning.py
  freqtrade/misc.py
  freqtrade/optimize/backtesting.py
  freqtrade/optimize/hyperopt.py
  freqtrade/plot/plotting.py
  freqtrade/strategy/interface.py
  tests/commands/test_commands.py
  tests/data/test_converter.py
  tests/data/test_history.py
  tests/optimize/test_backtesting.py
  tests/optimize/test_hyperopt.py
  tests/strategy/test_interface.py
  tests/test_misc.py
Labels: Enhancement

#2945 Kraken stoploss bugfix
  freqtrade/persistence.py
Labels: bug

#2879 Sortino hyperopt loss
  docs/bot-usage.md
  docs/hyperopt.md
  freqtrade/commands/cli_options.py
  freqtrade/optimize/hyperopt_loss_sortino.py
  freqtrade/optimize/hyperopt_loss_sortino_daily.py
  tests/optimize/test_hyperopt.py
Labels: hyperopt

#2999 [minor] improve and correct release documentation
  docs/developer.md
Labels: Documentation

#3001 [minor] Add note about InvalidNonce to documentation
  docs/exchanges.md
Labels: Documentation
