Repository freqtrade/freqtrade, pull requests merged in 2020-07, with the labels that each got.

#3497 Analyze dataframe and keep it until the next analysis
  docs/bot-basics.md
  docs/hyperopt.md
  docs/strategy-advanced.md
  docs/strategy-customization.md
  freqtrade/constants.py
  freqtrade/data/dataprovider.py
  freqtrade/freqtradebot.py
  freqtrade/strategy/interface.py
  freqtrade/strategy/strategy_wrapper.py
  freqtrade/templates/subtemplates/strategy_methods_advanced.j2
  mkdocs.yml
  tests/conftest.py
  tests/data/test_dataprovider.py
  tests/strategy/test_interface.py
  tests/test_freqtradebot.py
  tests/test_integration.py
Labels: Enhancement

#3589 [minor] Send timeframe min and ms in show_config response
  freqtrade/rpc/rpc.py
  tests/rpc/test_rpc_apiserver.py
Labels: RPC

#3582 List available backtesting data
  docs/data-download.md
  freqtrade/commands/__init__.py
  freqtrade/commands/arguments.py
  freqtrade/commands/data_commands.py
  freqtrade/data/history/idatahandler.py
  freqtrade/data/history/jsondatahandler.py
  tests/commands/test_commands.py
  tests/data/test_history.py
Labels: Enhancement

#3596 Allow 0 fee value by correctly checking for None
  freqtrade/optimize/backtesting.py
  tests/optimize/test_backtesting.py
Labels: Bug

#3606 Improve informative pair sample
  docs/strategy-customization.md
Labels: Documentation

#3613 Add trade_id to webhooks
  docs/webhook-config.md
  freqtrade/freqtradebot.py
  tests/rpc/test_rpc_telegram.py
  tests/test_freqtradebot.py
Labels: RPC

#3616 Fix pairfilter crash
  freqtrade/pairlist/PriceFilter.py
  tests/conftest.py
  tests/pairlist/test_pairlist.py
Labels: Bug

#3609 Add telegram /trades command
  docs/telegram-usage.md
  freqtrade/rpc/rpc.py
  freqtrade/rpc/telegram.py
  tests/commands/test_commands.py
  tests/conftest.py
  tests/data/test_btanalysis.py
  tests/rpc/test_rpc.py
  tests/rpc/test_rpc_apiserver.py
  tests/rpc/test_rpc_telegram.py
  tests/test_freqtradebot.py
  tests/test_persistence.py
Labels: RPC
