Repository freqtrade/freqtrade, pull requests merged in 2020-11, with the labels that each got.

#3857 Convert timestamp to int_timestamp for all arrow occurances
  freqtrade/commands/data_commands.py
  freqtrade/configuration/timerange.py
  freqtrade/data/dataprovider.py
  freqtrade/edge/edge_positioning.py
  freqtrade/exchange/exchange.py
  freqtrade/optimize/optimize_reports.py
  freqtrade/wallets.py
  setup.py
  tests/commands/test_commands.py
  tests/conftest.py
  tests/data/test_history.py
  tests/edge/test_edge.py
  tests/exchange/test_exchange.py
Labels: Tech debt

#3923 Rpc/combine profit fields
  freqtrade/persistence/models.py
  freqtrade/rpc/rpc.py
  freqtrade/rpc/telegram.py
  tests/rpc/test_rpc.py
  tests/rpc/test_rpc_apiserver.py
  tests/rpc/test_rpc_telegram.py
  tests/test_persistence.py
Labels: RPC

#3971 Fix bug when converting trades do ohlcv and no trades are available.
  freqtrade/constants.py
  freqtrade/data/converter.py
  freqtrade/data/history/hdf5datahandler.py
  freqtrade/data/history/history_utils.py
  freqtrade/data/history/idatahandler.py
  freqtrade/data/history/jsondatahandler.py
  tests/data/test_converter.py
  tests/data/test_history.py
Labels: Bug, Data download

#3996 Fix/doublelog
  freqtrade/loggers.py
  tests/test_configuration.py
Labels: Bug

#3997 Kraken stoploss-limit
  docs/exchanges.md
  docs/stoploss.md
  freqtrade/exchange/kraken.py
  mkdocs.yml
  tests/exchange/test_kraken.py
Labels: Enhancement

#4002 [Documentation] Prevent unintended LaTeX rendering
  docs/stoploss.md
Labels: Documentation

#4006 Remove deprecated experimental settings
  freqtrade/configuration/deprecated_settings.py
  freqtrade/constants.py
  tests/test_configuration.py
Labels: Tech debt

#4012 Enhance backtesting summary report
  docs/backtesting.md
  freqtrade/optimize/optimize_reports.py
Labels: Backtest, Enhancement

#4009 [Pairlist] Add PerformanceFilter
  docs/includes/pairlists.md
  freqtrade/constants.py
  freqtrade/pairlist/PerformanceFilter.py
  tests/pairlist/test_pairlist.py
Labels: Enhancement, Pairlist
