Repository freqtrade/freqtrade, pull requests merged in 2020-03, with the labels that each got.

#2982 Rate side configurable
  config_full.json.example
  docs/configuration.md
  freqtrade/constants.py
  freqtrade/freqtradebot.py
  freqtrade/templates/base_config.json.j2
  tests/rpc/test_rpc.py
  tests/rpc/test_rpc_apiserver.py
  tests/rpc/test_rpc_telegram.py
  tests/test_freqtradebot.py
Labels: Enhancement

#3018 Max drawdown in plot-profit
  docs/plotting.md
  freqtrade/data/btanalysis.py
  freqtrade/plot/plotting.py
  tests/data/test_btanalysis.py
  tests/test_plotting.py
Labels: Enhancement, Plotting

#2994 Added dynamic print table function to hyperopt
  freqtrade/commands/hyperopt_commands.py
  freqtrade/optimize/hyperopt.py
  tests/optimize/test_hyperopt.py
Labels: Enhancement

#3062 Plotting: Fix if no file exists and new skip option
  docs/plotting.md
  freqtrade/commands/arguments.py
  freqtrade/commands/cli_options.py
  freqtrade/configuration/configuration.py
  freqtrade/data/btanalysis.py
  freqtrade/plot/plotting.py
  tests/data/test_btanalysis.py
Labels: Plotting

#3096 Update max_open_trades documentation
  docs/configuration.md
Labels: Documentation

#3090 Remove partial candle documentation
  docs/exchanges.md
Labels: Documentation

#3121 [minor] Remove defaultstrategy occurance from docs
  docs/bot-usage.md
Labels: Documentation

#3126 [minor] Plot percent correctly
  freqtrade/plot/plotting.py
Labels: Plotting
