Repository freqtrade/freqtrade, pull requests merged in 2021-08, with the labels that each got.

#5245 Range stability filter max
  docs/includes/pairlists.md
  freqtrade/plugins/pairlist/rangestabilityfilter.py
  tests/plugins/test_pairlist.py
Labels: Enhancement, Pairlist

#5350 Add environment variable support
  docs/configuration.md
  freqtrade/configuration/configuration.py
  freqtrade/configuration/environment_vars.py
  freqtrade/constants.py
  tests/test_configuration.py
Labels: Enhancement

#5157 Margin db
  docs/leverage.md
  freqtrade/enums/__init__.py
  freqtrade/enums/interestmode.py
  freqtrade/freqtradebot.py
  freqtrade/persistence/migrations.py
  freqtrade/persistence/models.py
  mkdocs.yml
  tests/conftest.py
  tests/conftest_trades.py
  tests/rpc/test_rpc.py
  tests/test_freqtradebot.py
  tests/test_persistence.py
Labels: Enhancement, Non-spot

#5360 Hyperopt protections and Boolean parameter
  docs/hyperopt.md
  docs/includes/protections.md
  freqtrade/commands/cli_options.py
  freqtrade/configuration/deprecated_settings.py
  freqtrade/optimize/backtesting.py
  freqtrade/optimize/hyperopt.py
  freqtrade/optimize/hyperopt_auto.py
  freqtrade/optimize/hyperopt_interface.py
  freqtrade/optimize/hyperopt_tools.py
  freqtrade/plugins/protections/iprotection.py
  freqtrade/resolvers/strategy_resolver.py
  freqtrade/strategy/__init__.py
  freqtrade/strategy/hyper.py
  freqtrade/templates/base_strategy.py.j2
  freqtrade/templates/sample_strategy.py
  tests/optimize/test_hyperopt.py
  tests/strategy/strats/hyperoptable_strategy.py
  tests/strategy/test_interface.py
  tests/test_configuration.py
Labels: Enhancement, Hyperopt

#5365 Added leverage enums
  freqtrade/enums/__init__.py
  freqtrade/enums/collateral.py
  freqtrade/enums/tradingmode.py
  freqtrade/leverage/__init__.py
Labels: Non-spot

#5374 Remove legacy hyperopt
  freqtrade/commands/hyperopt_commands.py
  freqtrade/optimize/hyperopt_epoch_filters.py
  freqtrade/optimize/hyperopt_tools.py
  tests/commands/test_commands.py
  tests/conftest.py
Labels: Tech maintenance

#5380 Replaced the term margin with leverage when it should say leverage (All comments)
  freqtrade/persistence/migrations.py
  freqtrade/persistence/models.py
  tests/conftest_trades.py
  tests/test_persistence.py
Labels: Non-spot

#5381 Changed interest implementation (Margin)
  freqtrade/enums/__init__.py
  freqtrade/enums/interestmode.py
  freqtrade/leverage/__init__.py
  freqtrade/leverage/interest.py
  freqtrade/persistence/migrations.py
  freqtrade/persistence/models.py
  tests/conftest_trades.py
  tests/leverage/test_leverage.py
  tests/test_persistence.py
Labels: Non-spot

#5391 Fix recently introduced lookahead bias in backtesting
  freqtrade/optimize/backtesting.py
  tests/optimize/test_backtesting.py
Labels: Bug

#5395 Stream hyperopt-result in small batches
  freqtrade/optimize/hyperopt_epoch_filters.py
  freqtrade/optimize/hyperopt_tools.py
  tests/commands/test_commands.py
  tests/optimize/test_hyperopt_tools.py
Labels: Hyperopt

#5434 Fix no-event-loop available
  freqtrade/rpc/api_server/uvicorn_threaded.py
Labels: Bug

#5347 Custom order price
  docs/bot-basics.md
  docs/configuration.md
  docs/strategy-advanced.md
  freqtrade/constants.py
  freqtrade/freqtradebot.py
  freqtrade/strategy/interface.py
  tests/test_freqtradebot.py
Labels: Enhancement

#5456 Download-data log process added
  freqtrade/data/history/history_utils.py
  tests/data/test_history.py
Labels: Data download

#5447 Lev strat name changes
  freqtrade/optimize/backtesting.py
  freqtrade/resolvers/strategy_resolver.py
  freqtrade/strategy/interface.py
  freqtrade/strategy/strategy_helper.py
  freqtrade/templates/sample_hyperopt.py
  freqtrade/templates/sample_hyperopt_advanced.py
  tests/optimize/hyperopts/default_hyperopt.py
  tests/strategy/strats/hyperoptable_strategy.py
  tests/strategy/test_interface.py
  tests/strategy/test_strategy_loading.py
Labels: Non-spot
