Repository freqtrade/freqtrade, pull requests merged in 2021-02, with the labels that each got.

#4300 Extract min stake amount from bot to exchange class
  freqtrade/exchange/exchange.py
  freqtrade/freqtradebot.py
  tests/exchange/test_exchange.py
  tests/test_freqtradebot.py
Labels: Tech debt

#4301 Doc reorg
  docs/backtesting.md
  docs/bot-basics.md
  docs/bot-usage.md
  docs/configuration.md
  docs/developer.md
  docs/edge.md
  docs/hyperopt.md
  docs/includes/pricing.md
  docs/utils.md
  mkdocs.yml
Labels: Documentation

#4285 Deploy FreqUI into webserver
  .gitignore
  Dockerfile
  Dockerfile.armhf
  MANIFEST.in
  docker-compose.yml
  docs/rest-api.md
  freqtrade/commands/__init__.py
  freqtrade/commands/arguments.py
  freqtrade/commands/cli_options.py
  freqtrade/commands/deploy_commands.py
  freqtrade/rpc/api_server/ui/fallback_file.html
  freqtrade/rpc/api_server/ui/favicon.ico
  freqtrade/rpc/api_server/ui/installed/.gitkeep
  freqtrade/rpc/api_server/web_ui.py
  freqtrade/rpc/api_server/webserver.py
  mkdocs.yml
  requirements.txt
  tests/commands/test_commands.py
  tests/rpc/test_rpc_apiserver.py
Labels: Enhancement

#4309 Move get_trade_stake_amount to wallets
  freqtrade/freqtradebot.py
  freqtrade/rpc/rpc.py
  freqtrade/wallets.py
  tests/test_freqtradebot.py
  tests/test_integration.py
Labels: Tech debt

#4446 Webhook JSON format
  docs/webhook-config.md
  freqtrade/rpc/webhook.py
  tests/rpc/test_rpc_webhook.py
Labels: RPC
