Repository freqtrade/freqtrade, pull requests merged in 2021-12, with the labels that each got.

#6011 correctly apply leverage to backtesting
  freqtrade/optimize/backtesting.py
  tests/optimize/__init__.py
  tests/optimize/test_backtest_detail.py
Labels: Non-spot

#5929 Telegram and log prints strategy version.
  docs/strategy-advanced.md
  freqtrade/rpc/api_server/api_schemas.py
  freqtrade/rpc/api_server/api_v1.py
  freqtrade/rpc/rpc.py
  freqtrade/rpc/telegram.py
  freqtrade/strategy/interface.py
  freqtrade/worker.py
  tests/rpc/test_rpc_apiserver.py
  tests/rpc/test_rpc_telegram.py
Labels: RPC

#5780 Mark price candles
  docs/data-download.md
  freqtrade/commands/arguments.py
  freqtrade/commands/cli_options.py
  freqtrade/commands/data_commands.py
  freqtrade/configuration/configuration.py
  freqtrade/constants.py
  freqtrade/data/converter.py
  freqtrade/data/dataprovider.py
  freqtrade/data/history/hdf5datahandler.py
  freqtrade/data/history/history_utils.py
  freqtrade/data/history/idatahandler.py
  freqtrade/data/history/jsondatahandler.py
  freqtrade/edge/edge_positioning.py
  freqtrade/enums/__init__.py
  freqtrade/enums/candletype.py
  freqtrade/exchange/binance.py
  freqtrade/exchange/common.py
  freqtrade/exchange/exchange.py
  freqtrade/exchange/ftx.py
  freqtrade/exchange/kraken.py
  freqtrade/misc.py
  freqtrade/optimize/backtesting.py
  freqtrade/plugins/pairlist/AgeFilter.py
  freqtrade/plugins/pairlist/ShuffleFilter.py
  freqtrade/plugins/pairlist/VolatilityFilter.py
  freqtrade/plugins/pairlist/VolumePairList.py
  freqtrade/plugins/pairlist/rangestabilityfilter.py
  freqtrade/plugins/pairlistmanager.py
  freqtrade/rpc/api_server/api_v1.py
  freqtrade/strategy/informative_decorator.py
  freqtrade/strategy/interface.py
  tests/commands/test_commands.py
  tests/conftest.py
  tests/data/test_converter.py
  tests/data/test_dataprovider.py
  tests/data/test_history.py
  tests/exchange/test_binance.py
  tests/exchange/test_ccxt_compat.py
  tests/exchange/test_exchange.py
  tests/leverage/test_candletype.py
  tests/optimize/test_backtesting.py
  tests/plugins/test_pairlist.py
  tests/rpc/test_rpc_apiserver.py
  tests/strategy/strats/informative_decorator_strategy.py
  tests/strategy/test_interface.py
  tests/strategy/test_strategy_helpers.py
  tests/test_freqtradebot.py
  tests/test_misc.py
  tests/testdata/futures/UNITTEST_USDT-1h-mark.h5
  tests/testdata/futures/UNITTEST_USDT-1h-mark.json
  tests/testdata/futures/XRP_USDT-1h-futures.json
  tests/testdata/futures/XRP_USDT-1h-futures.json.gz
  tests/testdata/futures/XRP_USDT-1h-mark.json
Labels: Non-spot

#6045 Add unknown_fee_rate parameter
  docs/configuration.md
  docs/exchanges.md
  freqtrade/constants.py
  freqtrade/exchange/exchange.py
  tests/exchange/test_exchange.py
Labels: Enhancement

#6055 Add Blacklist delete
  freqtrade/rpc/api_server/api_v1.py
  freqtrade/rpc/rpc.py
  freqtrade/rpc/telegram.py
  tests/rpc/test_rpc.py
  tests/rpc/test_rpc_apiserver.py
  tests/rpc/test_rpc_telegram.py
Labels: Enhancement, RPC

#6043 Funding fees
  freqtrade/data/history/history_utils.py
  freqtrade/exchange/exchange.py
  freqtrade/exchange/okex.py
  tests/data/test_history.py
  tests/exchange/test_ccxt_compat.py
  tests/exchange/test_exchange.py
  tests/test_freqtradebot.py
Labels: Non-spot

#6070 Suppress additional logs for pairs in blacklist
  freqtrade/plugins/pairlistmanager.py
  tests/plugins/test_pairlist.py
Labels: Pairlist

#6107 Update CI to notify on discord only
  .github/workflows/ci.yml
Labels: Tech maintenance

#6112 Fix test not running when user_data contains historical data.
  tests/optimize/test_hyperopt.py
Labels: Tech maintenance

#6128 Futures fixes
  freqtrade/data/dataprovider.py
  freqtrade/exchange/exchange.py
  freqtrade/plugins/pairlistmanager.py
  freqtrade/strategy/interface.py
Labels: Non-spot

#6127 Download data futures fix
  freqtrade/data/history/history_utils.py
  freqtrade/optimize/backtesting.py
  tests/data/test_history.py
Labels: Non-spot

#6084 Telegram and Webhook updates
  docs/telegram-usage.md
  docs/webhook-config.md
  freqtrade/freqtradebot.py
  freqtrade/rpc/rpc.py
  freqtrade/rpc/telegram.py
  freqtrade/rpc/webhook.py
  tests/rpc/test_rpc_telegram.py
  tests/rpc/test_rpc_webhook.py
  tests/test_freqtradebot.py
Labels: Non-spot

#5677 Update CI to run on python 3.10
  .github/workflows/ci.yml
  Dockerfile
  README.md
  build_helpers/TA_Lib-0.4.22-cp310-cp310-win_amd64.whl
  build_helpers/install_windows.ps1
  docs/advanced-setup.md
  docs/installation.md
  docs/windows_installation.md
  pyproject.toml
  requirements.txt
  setup.cfg
  setup.sh
Labels: WIP, Tech maintenance

#6140 Change sequence of ROI/sell signal to favor sell-signal
  docs/backtesting.md
  freqtrade/strategy/interface.py
  tests/optimize/test_backtest_detail.py
Labels: Backtest

#6133 Reduce memory usage by not holding on to no longer needed data
  freqtrade/optimize/backtesting.py
  tests/optimize/test_backtesting.py
Labels: Backtest

#6143 Todos
  docs/leverage.md
  freqtrade/commands/hyperopt_commands.py
  freqtrade/exchange/binance.py
  freqtrade/freqtradebot.py
  freqtrade/persistence/models.py
  freqtrade/plugins/pairlistmanager.py
  freqtrade/plugins/protections/max_drawdown_protection.py
  freqtrade/plugins/protections/stoploss_guard.py
  freqtrade/rpc/rpc.py
  freqtrade/rpc/telegram.py
  tests/exchange/test_exchange.py
  tests/exchange/test_kraken.py
  tests/test_freqtradebot.py
Labels: Non-spot
