Repository freqtrade/freqtrade, pull requests merged in 2021-11, with the labels that each got.

#5150 Adding command for Filtering and print trades
  docs/utils.md
  freqtrade/commands/__init__.py
  freqtrade/commands/arguments.py
  freqtrade/commands/cli_options.py
  freqtrade/commands/optimize_commands.py
  freqtrade/configuration/configuration.py
  freqtrade/optimize/optimize_reports.py
  tests/commands/test_commands.py
  tests/optimize/test_optimize_reports.py
Labels: Enhancement, WIP, Backtest

#5710 Added SELL_TAG for trading, backtesting and telegram
  freqtrade/enums/signaltype.py
  freqtrade/freqtradebot.py
  freqtrade/optimize/backtesting.py
  freqtrade/optimize/optimize_reports.py
  freqtrade/persistence/models.py
  freqtrade/rpc/api_server/api_schemas.py
  freqtrade/rpc/rpc.py
  freqtrade/rpc/telegram.py
  freqtrade/strategy/interface.py
  tests/conftest.py
  tests/conftest_trades.py
  tests/optimize/__init__.py
  tests/optimize/test_backtesting.py
  tests/rpc/test_rpc.py
  tests/rpc/test_rpc_apiserver.py
  tests/rpc/test_rpc_telegram.py
  tests/strategy/test_interface.py
  tests/test_freqtradebot.py
  tests/test_persistence.py
Labels: Enhancement, WIP, RPC

#5668 Docs for leverage
  docs/configuration.md
  docs/exchanges.md
  docs/leverage.md
Labels: Documentation, Non-spot

#5846 Add /weekly and /monthly to Telegram (#5527)
  docs/telegram-usage.md
  freqtrade/rpc/rpc.py
  freqtrade/rpc/telegram.py
  requirements-dev.txt
  requirements.txt
  tests/rpc/test_rpc_telegram.py
Labels: RPC

#5850 multiple exit-timeouts can trigger emergencysell
  config_examples/config_full.example.json
  docs/configuration.md
  freqtrade/constants.py
  freqtrade/freqtradebot.py
  freqtrade/persistence/models.py
  tests/test_freqtradebot.py
  tests/test_persistence.py
Labels: Enhancement

#5853 Added okex exchange class futures properties
  freqtrade/exchange/okex.py
Labels: Non-spot

#5843 Update warning message open trades
  freqtrade/freqtradebot.py
Labels: RPC

#5879 Improve pct formatting
  freqtrade/data/converter.py
  freqtrade/optimize/hyperopt_tools.py
  freqtrade/optimize/optimize_reports.py
  freqtrade/persistence/models.py
  freqtrade/plot/plotting.py
  freqtrade/plugins/pairlist/PriceFilter.py
  freqtrade/plugins/pairlist/SpreadFilter.py
  freqtrade/rpc/api_server/api_schemas.py
  freqtrade/rpc/rpc.py
  freqtrade/rpc/telegram.py
  freqtrade/strategy/interface.py
  tests/rpc/test_rpc.py
  tests/rpc/test_rpc_apiserver.py
  tests/rpc/test_rpc_telegram.py
  tests/test_freqtradebot.py
  tests/test_plotting.py
Labels: Tech maintenance

#5889 TODO-lev trim
  freqtrade/exchange/binance.py
  freqtrade/exchange/bybit.py
  freqtrade/exchange/ftx.py
  freqtrade/exchange/gateio.py
  freqtrade/exchange/kraken.py
  freqtrade/exchange/okex.py
  freqtrade/freqtradebot.py
  freqtrade/persistence/models.py
  freqtrade/plugins/protections/stoploss_guard.py
  tests/conftest_trades.py
  tests/rpc/test_rpc_apiserver.py
  tests/rpc/test_rpc_telegram.py
  tests/strategy/test_default_strategy.py
  tests/test_persistence.py
Labels: Non-spot

#5885 Include more details in _FILL telegram notifications
  freqtrade/rpc/telegram.py
  tests/rpc/test_rpc_telegram.py
Labels: Enhancement, RPC

#5887 Common ccxt config
  freqtrade/exchange/bibox.py
  freqtrade/exchange/binance.py
  freqtrade/exchange/bybit.py
  freqtrade/exchange/exchange.py
  freqtrade/exchange/gateio.py
  freqtrade/exchange/okex.py
  tests/exchange/test_exchange.py
Labels: Non-spot

#5779 Funding fee dry run
  freqtrade/exchange/bibox.py
  freqtrade/exchange/binance.py
  freqtrade/exchange/bybit.py
  freqtrade/exchange/exchange.py
  freqtrade/exchange/ftx.py
  freqtrade/exchange/gateio.py
  freqtrade/exchange/hitbtc.py
  freqtrade/exchange/kraken.py
  freqtrade/exchange/kucoin.py
  freqtrade/exchange/okex.py
  freqtrade/freqtradebot.py
  tests/conftest.py
  tests/exchange/test_ccxt_compat.py
  tests/exchange/test_exchange.py
  tests/test_freqtradebot.py
Labels: Non-spot

#5825 Futures pairlist
  freqtrade/commands/arguments.py
  freqtrade/commands/cli_options.py
  freqtrade/commands/list_commands.py
  freqtrade/configuration/configuration.py
  freqtrade/exchange/binance.py
  freqtrade/exchange/exchange.py
  freqtrade/exchange/ftx.py
  requirements.txt
  setup.py
  tests/commands/test_commands.py
  tests/conftest.py
  tests/exchange/test_ccxt_compat.py
  tests/exchange/test_exchange.py
Labels: Non-spot

#5890 Todo-lev RPC tests and model
  freqtrade/rpc/api_server/api_schemas.py
  freqtrade/rpc/rpc.py
  tests/conftest.py
  tests/conftest_trades.py
  tests/rpc/test_rpc_apiserver.py
  tests/rpc/test_rpc_telegram.py
  tests/test_freqtradebot.py
Labels: Non-spot

#5924 call leverage methods
  docs/backtesting.md
  docs/bot-basics.md
  freqtrade/data/btanalysis.py
  freqtrade/freqtradebot.py
  freqtrade/optimize/backtesting.py
  freqtrade/optimize/optimize_reports.py
  tests/optimize/test_backtesting.py
  tests/optimize/test_hyperopt.py
  tests/optimize/test_optimize_reports.py
  tests/test_freqtradebot.py
Labels: Non-spot

#5953 Is future method fix
  freqtrade/exchange/binance.py
  freqtrade/exchange/exchange.py
  freqtrade/exchange/ftx.py
  tests/exchange/test_exchange.py
Labels: Non-spot

#5952 Update ARMHF image to 3.9
  Dockerfile
  docker/Dockerfile.armhf
Labels: Tech maintenance, Docker

#5935 Short buy tag compat
  docs/deprecated.md
  docs/strategy-advanced.md
  docs/strategy-customization.md
  docs/webhook-config.md
  freqtrade/data/btanalysis.py
  freqtrade/freqtradebot.py
  freqtrade/optimize/backtesting.py
  freqtrade/optimize/optimize_reports.py
  freqtrade/persistence/migrations.py
  freqtrade/persistence/models.py
  freqtrade/rpc/api_server/api_schemas.py
  freqtrade/rpc/rpc.py
  freqtrade/rpc/telegram.py
  tests/conftest.py
  tests/conftest_trades.py
  tests/optimize/test_backtest_detail.py
  tests/optimize/test_backtesting.py
  tests/rpc/test_rpc.py
  tests/rpc/test_rpc_apiserver.py
  tests/rpc/test_rpc_telegram.py
  tests/test_freqtradebot.py
  tests/test_persistence.py
Labels: Non-spot

#5976 allow force options with ordertype
  freqtrade/freqtradebot.py
  freqtrade/rpc/api_server/api_schemas.py
  freqtrade/rpc/api_server/api_v1.py
  freqtrade/rpc/rpc.py
  tests/rpc/test_rpc.py
Labels: Enhancement, RPC
