Repository freqtrade/freqtrade, pull requests merged in 2021-06, with the labels that each got.

#5069 Pricing refactor
  freqtrade/exchange/exchange.py
  freqtrade/exchange/ftx.py
  freqtrade/freqtradebot.py
  freqtrade/rpc/rpc.py
  tests/exchange/test_exchange.py
  tests/rpc/test_rpc.py
  tests/rpc/test_rpc_apiserver.py
  tests/test_freqtradebot.py
Labels: Tech debt

#4982 day/week options for Telegram '/profit' command
  README.md
  docs/telegram-usage.md
  freqtrade/rpc/rpc.py
  freqtrade/rpc/telegram.py
  tests/rpc/test_rpc_telegram.py
Labels: Enhancement, RPC

#5104 Enums own package
  freqtrade/commands/data_commands.py
  freqtrade/commands/deploy_commands.py
  freqtrade/commands/hyperopt_commands.py
  freqtrade/commands/list_commands.py
  freqtrade/commands/optimize_commands.py
  freqtrade/commands/pairlist_commands.py
  freqtrade/commands/plot_commands.py
  freqtrade/configuration/check_exchange.py
  freqtrade/configuration/config_setup.py
  freqtrade/configuration/config_validation.py
  freqtrade/configuration/configuration.py
  freqtrade/data/dataprovider.py
  freqtrade/edge/edge_positioning.py
  freqtrade/enums/__init__.py
  freqtrade/enums/rpcmessagetype.py
  freqtrade/enums/runmode.py
  freqtrade/enums/selltype.py
  freqtrade/enums/signaltype.py
  freqtrade/enums/state.py
  freqtrade/freqtradebot.py
  freqtrade/optimize/backtesting.py
  freqtrade/persistence/models.py
  freqtrade/plugins/protections/stoploss_guard.py
  freqtrade/rpc/__init__.py
  freqtrade/rpc/rpc.py
  freqtrade/rpc/rpc_manager.py
  freqtrade/rpc/telegram.py
  freqtrade/rpc/webhook.py
  freqtrade/strategy/hyper.py
  freqtrade/strategy/interface.py
  freqtrade/wallets.py
  freqtrade/worker.py
  tests/commands/test_commands.py
  tests/conftest.py
  tests/data/test_dataprovider.py
  tests/edge/test_edge.py
  tests/optimize/__init__.py
  tests/optimize/conftest.py
  tests/optimize/test_backtest_detail.py
  tests/optimize/test_backtesting.py
  tests/optimize/test_edge_cli.py
  tests/optimize/test_hyperopt.py
  tests/optimize/test_optimize_reports.py
  tests/plugins/test_protections.py
  tests/rpc/test_rpc.py
  tests/rpc/test_rpc_apiserver.py
  tests/rpc/test_rpc_manager.py
  tests/rpc/test_rpc_telegram.py
  tests/rpc/test_rpc_webhook.py
  tests/strategy/test_interface.py
  tests/test_configuration.py
  tests/test_freqtradebot.py
  tests/test_integration.py
  tests/test_main.py
  tests/test_worker.py
Labels: Tech debt

#5126 Remove ordereddict
  freqtrade/commands/list_commands.py
  freqtrade/optimize/hyperopt_tools.py
  freqtrade/resolvers/strategy_resolver.py
  tests/strategy/test_strategy_loading.py
Labels: Tech debt

#5108 Implement most pessimistic handling of trailing stoploss.
  docs/backtesting.md
  freqtrade/optimize/backtesting.py
  freqtrade/strategy/interface.py
  tests/optimize/test_backtest_detail.py
Labels: Backtest

#5014 BugFix - `hyperopt-show --print-json` include non-optimized params
  freqtrade/optimize/hyperopt_tools.py
Labels: Hyperopt

#4308 Add Refresh / Reload Button on rpc/Telegram
  config_full.json.example
  docs/telegram-usage.md
  freqtrade/constants.py
  freqtrade/rpc/telegram.py
  tests/rpc/test_rpc_telegram.py
Labels: Enhancement, RPC

#5152 Fix errors during ubuntu install
  docs/installation.md
Labels: Install

#5170 make "/profit N" command output be consistent with "/daily" command
  freqtrade/rpc/rpc.py
  freqtrade/rpc/telegram.py
Labels: RPC

#5082 Dry run order filling
  docs/configuration.md
  freqtrade/exchange/exchange.py
  tests/conftest.py
  tests/exchange/test_exchange.py
  tests/rpc/test_rpc.py
  tests/rpc/test_rpc_apiserver.py
  tests/rpc/test_rpc_telegram.py
  tests/test_freqtradebot.py
Labels: Enhancement

#5178 spell corrections
  freqtrade/commands/build_config_commands.py
  freqtrade/configuration/configuration.py
  freqtrade/constants.py
  freqtrade/data/converter.py
  freqtrade/edge/edge_positioning.py
  freqtrade/exceptions.py
  freqtrade/exchange/exchange.py
  freqtrade/exchange/kraken.py
  freqtrade/freqtradebot.py
  freqtrade/optimize/backtesting.py
  freqtrade/optimize/optimize_reports.py
  freqtrade/plot/plotting.py
  freqtrade/plugins/pairlist/PerformanceFilter.py
  freqtrade/resolvers/iresolver.py
  freqtrade/rpc/fiat_convert.py
  freqtrade/rpc/rpc.py
  freqtrade/rpc/telegram.py
  freqtrade/strategy/hyper.py
  freqtrade/strategy/interface.py
  freqtrade/worker.py
Labels: Documentation

#5183 Remove order book max
  config_binance.json.example
  config_bittrex.json.example
  config_ftx.json.example
  config_full.json.example
  config_kraken.json.example
  docs/configuration.md
  docs/deprecated.md
  docs/includes/pricing.md
  freqtrade/configuration/config_validation.py
  freqtrade/constants.py
  freqtrade/exchange/exchange.py
  freqtrade/freqtradebot.py
  freqtrade/templates/base_config.json.j2
  tests/conftest.py
  tests/exchange/test_exchange.py
  tests/test_configuration.py
  tests/test_freqtradebot.py
Labels: Tech debt

#5188 Move ask_strategy config settings to root level
  config_binance.json.example
  config_bittrex.json.example
  config_ftx.json.example
  config_full.json.example
  config_kraken.json.example
  docs/configuration.md
  freqtrade/configuration/config_validation.py
  freqtrade/configuration/deprecated_settings.py
  freqtrade/constants.py
  freqtrade/freqtradebot.py
  freqtrade/optimize/optimize_reports.py
  freqtrade/resolvers/strategy_resolver.py
  freqtrade/strategy/interface.py
  freqtrade/templates/base_config.json.j2
  tests/optimize/test_backtest_detail.py
  tests/optimize/test_backtesting.py
  tests/strategy/test_strategy_loading.py
  tests/test_configuration.py
  tests/test_freqtradebot.py
Labels: Tech debt
