Repository freqtrade/freqtrade, pull requests merged in 2021-09, with the labels that each got.

#5413 Add backtest-detail to allow intra-candle backtests
  docs/backtesting.md
  freqtrade/commands/arguments.py
  freqtrade/commands/cli_options.py
  freqtrade/configuration/configuration.py
  freqtrade/optimize/backtesting.py
  freqtrade/optimize/optimize_reports.py
  freqtrade/rpc/api_server/api_backtest.py
  freqtrade/rpc/api_server/api_schemas.py
  tests/optimize/test_backtesting.py
Labels: Enhancement, Backtest

#5531 Exclude some parts from coverage that can't really be tested
  freqtrade/__init__.py
  freqtrade/loggers.py
Labels: Tech maintenance

#5544 New pair download improvement
  freqtrade/data/history/history_utils.py
  freqtrade/exchange/binance.py
  freqtrade/exchange/exchange.py
  tests/exchange/test_binance.py
Labels: Data download

#5551 Comments todos formatting log messages
  freqtrade/commands/hyperopt_commands.py
  freqtrade/commands/list_commands.py
  freqtrade/enums/signaltype.py
  freqtrade/freqtradebot.py
  freqtrade/optimize/backtesting.py
  freqtrade/persistence/models.py
  freqtrade/plugins/pairlist/PrecisionFilter.py
  freqtrade/plugins/pairlistmanager.py
  freqtrade/plugins/protections/max_drawdown_protection.py
  freqtrade/plugins/protections/stoploss_guard.py
  freqtrade/rpc/rpc.py
  freqtrade/strategy/interface.py
  tests/test_freqtradebot.py
  tests/test_persistence.py
Labels: Non-spot

#5560 Don't blindly create coroutines, but fire them off in batches
  freqtrade/exchange/exchange.py
  tests/exchange/test_exchange.py
Labels: Data download

#5566 Remove legacy hyperopt
  .github/workflows/ci.yml
  .travis.yml
  README.md
  docs/advanced-hyperopt.md
  docs/bot-usage.md
  docs/deprecated.md
  docs/faq.md
  docs/hyperopt.md
  docs/utils.md
  freqtrade/commands/__init__.py
  freqtrade/commands/arguments.py
  freqtrade/commands/cli_options.py
  freqtrade/commands/deploy_commands.py
  freqtrade/commands/list_commands.py
  freqtrade/constants.py
  freqtrade/optimize/hyperopt.py
  freqtrade/optimize/hyperopt_auto.py
  freqtrade/optimize/hyperopt_interface.py
  freqtrade/resolvers/hyperopt_resolver.py
  freqtrade/templates/base_hyperopt.py.j2
  freqtrade/templates/sample_hyperopt.py
  freqtrade/templates/sample_hyperopt_advanced.py
  freqtrade/templates/subtemplates/hyperopt_buy_guards_full.j2
  freqtrade/templates/subtemplates/hyperopt_buy_guards_minimal.j2
  freqtrade/templates/subtemplates/hyperopt_buy_space_full.j2
  freqtrade/templates/subtemplates/hyperopt_buy_space_minimal.j2
  freqtrade/templates/subtemplates/hyperopt_sell_guards_full.j2
  freqtrade/templates/subtemplates/hyperopt_sell_guards_minimal.j2
  freqtrade/templates/subtemplates/hyperopt_sell_space_full.j2
  freqtrade/templates/subtemplates/hyperopt_sell_space_minimal.j2
  tests/commands/test_commands.py
  tests/exchange/test_exchange.py
  tests/optimize/conftest.py
  tests/optimize/hyperopts/hyperopt_test_sep_file.py
  tests/optimize/test_hyperopt.py
  tests/plugins/test_pairlocks.py
  tests/test_directory_operations.py
Labels: Hyperopt, Tech maintenance

#5574 Agefilter cache
  freqtrade/configuration/PeriodicCache.py
  freqtrade/configuration/__init__.py
  freqtrade/plugins/pairlist/AgeFilter.py
  requirements-dev.txt
  tests/plugins/test_pairlist.py
  tests/test_periodiccache.py
Labels: Pairlist

#5579 Parametrize test persistence
  freqtrade/persistence/models.py
  tests/conftest.py
  tests/test_persistence.py
Labels: Non-spot

#5580 Hyperopt set diff base estimators
  docs/advanced-hyperopt.md
  freqtrade/optimize/hyperopt.py
  freqtrade/optimize/hyperopt_auto.py
  freqtrade/optimize/hyperopt_interface.py
  tests/optimize/test_hyperopt.py
Labels: Enhancement, Hyperopt

#5582 Added days parameter to PerformanceFilter
  docs/includes/pairlists.md
  freqtrade/persistence/models.py
  freqtrade/plugins/pairlist/PerformanceFilter.py
  tests/plugins/test_pairlist.py
Labels: Pairlist

#5281 A decorator for easy creation of informative pairs
  docs/strategy-advanced.md
  docs/strategy-customization.md
  freqtrade/edge/edge_positioning.py
  freqtrade/freqtradebot.py
  freqtrade/optimize/backtesting.py
  freqtrade/optimize/edge_cli.py
  freqtrade/strategy/__init__.py
  freqtrade/strategy/informative_decorator.py
  freqtrade/strategy/interface.py
  freqtrade/strategy/strategy_helper.py
  tests/rpc/test_rpc_apiserver.py
  tests/strategy/strats/informative_decorator_strategy.py
  tests/strategy/test_interface.py
  tests/strategy/test_strategy_helpers.py
  tests/strategy/test_strategy_loading.py
Labels: Enhancement

#5541 [Feat/Short] Added Ftx Interest Calculation
  freqtrade/leverage/interest.py
  tests/leverage/test_interest.py
Labels: Non-spot

#5387 Lev exchange
  docs/leverage.md
  freqtrade/exchange/bibox.py
  freqtrade/exchange/binance.py
  freqtrade/exchange/binance_leverage_brackets.json
  freqtrade/exchange/exchange.py
  freqtrade/exchange/ftx.py
  freqtrade/exchange/kraken.py
  freqtrade/freqtradebot.py
  tests/conftest.py
  tests/exchange/test_binance.py
  tests/exchange/test_exchange.py
  tests/exchange/test_ftx.py
  tests/exchange/test_kraken.py
  tests/test_freqtradebot.py
Labels: Non-spot

#5593 Parametrized test freqtradebot
  tests/test_freqtradebot.py
Labels: Tech maintenance

#5598 Add docker troubleshooting information for win10/wsl
  docs/docker_quickstart.md
Labels: Documentation, Docker

#5599 Notify trigger protections
  config_examples/config_full.example.json
  docs/telegram-usage.md
  freqtrade/constants.py
  freqtrade/enums/rpcmessagetype.py
  freqtrade/freqtradebot.py
  freqtrade/persistence/pairlock_middleware.py
  freqtrade/plugins/protectionmanager.py
  freqtrade/rpc/telegram.py
  tests/plugins/test_protections.py
  tests/rpc/test_rpc_telegram.py
  tests/test_freqtradebot.py
Labels: RPC

#5605 fixed webhook "unsupported format string passed to NoneType." error
  freqtrade/freqtradebot.py
Labels: RPC

#5601 parameterize some tests
  tests/conftest.py
  tests/test_freqtradebot.py
Labels: Tech maintenance
