Repository freqtrade/freqtrade, pull requests merged in 2022-03, with the labels that each got.

#6487 setup.sh install gettext for mac
  setup.sh
Labels: Bug, Install

#6489 gateio market orders futures
  freqtrade/exchange/gateio.py
Labels: Non-spot

#6467 Liquidation price in backtesting
  docs/leverage.md
  freqtrade/exchange/exchange.py
  freqtrade/freqtradebot.py
  freqtrade/optimize/backtesting.py
  freqtrade/persistence/models.py
  tests/conftest.py
  tests/exchange/test_exchange.py
  tests/optimize/test_backtesting.py
  tests/test_freqtradebot.py
Labels: Non-spot

#6492 Merge develop into feat/short
  .gitignore
  README.md
  docs/assets/windows_install.png
  docs/exchanges.md
  docs/index.md
  docs/requirements-docs.txt
  docs/stoploss.md
  docs/windows_installation.md
  freqtrade/commands/build_config_commands.py
  freqtrade/commands/optimize_commands.py
  freqtrade/constants.py
  freqtrade/exchange/__init__.py
  freqtrade/exchange/binance.py
  freqtrade/exchange/exchange.py
  freqtrade/exchange/ftx.py
  freqtrade/exchange/huobi.py
  freqtrade/exchange/kraken.py
  freqtrade/exchange/kucoin.py
  freqtrade/freqtradebot.py
  freqtrade/persistence/models.py
  freqtrade/rpc/api_server/api_backtest.py
  freqtrade/rpc/api_server/api_schemas.py
  freqtrade/rpc/api_server/api_v1.py
  freqtrade/rpc/api_server/deps.py
  freqtrade/rpc/rpc.py
  freqtrade/rpc/telegram.py
  freqtrade/templates/subtemplates/exchange_huobi.j2
  requirements-dev.txt
  requirements.txt
  setup.py
  setup.sh
  tests/exchange/test_binance.py
  tests/exchange/test_ccxt_compat.py
  tests/exchange/test_exchange.py
  tests/exchange/test_huobi.py
  tests/exchange/test_kucoin.py
  tests/rpc/test_rpc.py
  tests/rpc/test_rpc_apiserver.py
  tests/rpc/test_rpc_telegram.py
  tests/test_freqtradebot.py
  tests/test_persistence.py
Labels: Non-spot

#6468 todos
  tests/test_freqtradebot.py
Labels: Non-spot

#6495 Simplify and align liquidation price handling
  freqtrade/freqtradebot.py
  freqtrade/persistence/models.py
  tests/test_freqtradebot.py
  tests/test_persistence.py
Labels: Non-spot

#6507 Update order time in force to use entry/exit wording
  config_examples/config_full.example.json
  docs/configuration.md
  freqtrade/configuration/config_validation.py
  freqtrade/constants.py
  freqtrade/freqtradebot.py
  freqtrade/optimize/backtesting.py
  freqtrade/resolvers/strategy_resolver.py
  freqtrade/strategy/interface.py
  freqtrade/templates/base_strategy.py.j2
  freqtrade/templates/sample_short_strategy.py
  freqtrade/templates/sample_strategy.py
  tests/optimize/test_backtesting.py
  tests/strategy/strats/hyperoptable_strategy.py
  tests/strategy/strats/strategy_test_v2.py
  tests/strategy/strats/strategy_test_v3.py
  tests/strategy/test_strategy_loading.py
  tests/test_configuration.py
Labels: Non-spot

#6522 Is short strat
  freqtrade/optimize/backtesting.py
  freqtrade/resolvers/strategy_resolver.py
  freqtrade/strategy/interface.py
  freqtrade/templates/base_strategy.py.j2
  freqtrade/templates/sample_short_strategy.py
  freqtrade/templates/sample_strategy.py
  tests/rpc/test_rpc_apiserver.py
  tests/strategy/strats/strategy_test_v3.py
  tests/strategy/test_interface.py
  tests/strategy/test_strategy_loading.py
Labels: Non-spot

#6512 Short order types renamal
  README.md
  config_examples/config_full.example.json
  docs/configuration.md
  docs/faq.md
  docs/includes/pricing.md
  docs/rest-api.md
  docs/sandbox-testing.md
  docs/sql_cheatsheet.md
  docs/stoploss.md
  docs/telegram-usage.md
  freqtrade/configuration/config_validation.py
  freqtrade/configuration/deprecated_settings.py
  freqtrade/constants.py
  freqtrade/freqtradebot.py
  freqtrade/optimize/backtesting.py
  freqtrade/rpc/api_server/api_schemas.py
  freqtrade/rpc/rpc.py
  freqtrade/rpc/telegram.py
  freqtrade/strategy/interface.py
  freqtrade/templates/base_strategy.py.j2
  freqtrade/templates/sample_short_strategy.py
  freqtrade/templates/sample_strategy.py
  freqtrade/templates/subtemplates/exchange_bittrex.j2
  tests/exchange/test_exchange.py
  tests/exchange/test_gateio.py
  tests/optimize/test_backtesting.py
  tests/strategy/strats/hyperoptable_strategy.py
  tests/strategy/strats/strategy_test_v2.py
  tests/strategy/strats/strategy_test_v3.py
  tests/strategy/test_strategy_loading.py
  tests/test_configuration.py
  tests/test_freqtradebot.py
  tests/test_integration.py
Labels: Non-spot

#6523 Update methods wording
  freqtrade/resolvers/strategy_resolver.py
  freqtrade/strategy/interface.py
  freqtrade/templates/base_strategy.py.j2
  freqtrade/templates/sample_short_strategy.py
  freqtrade/templates/sample_strategy.py
  freqtrade/templates/subtemplates/strategy_methods_advanced.j2
  tests/strategy/strats/broken_strats/broken_futures_strategies.py
  tests/strategy/strats/strategy_test_v3.py
  tests/strategy/test_default_strategy.py
  tests/strategy/test_interface.py
  tests/strategy/test_strategy_loading.py
Labels: Non-spot

#6513 Gateio stoploss on exchange
  docs/exchanges.md
  docs/stoploss.md
  freqtrade/exchange/exchange.py
  freqtrade/exchange/gateio.py
  tests/exchange/test_gateio.py
Labels: Enhancement, Stoploss

#6537 Add BT's leverage and short calculation
  freqtrade/optimize/backtesting.py
  tests/optimize/test_backtesting.py
Labels: Non-spot

#6547 Short bt tests
  freqtrade/optimize/backtesting.py
  freqtrade/strategy/interface.py
  tests/optimize/__init__.py
  tests/optimize/test_backtest_detail.py
Labels: Non-spot

#6550 Short tickerproblems
  freqtrade/exchange/binance.py
  freqtrade/exchange/exchange.py
  freqtrade/exchange/okx.py
  freqtrade/misc.py
  freqtrade/plugins/pairlist/VolumePairList.py
  tests/conftest.py
  tests/exchange/test_ccxt_compat.py
  tests/exchange/test_exchange.py
  tests/exchange/test_gateio.py
  tests/plugins/test_pairlist.py
  tests/test_misc.py
Labels: Non-spot

#6555 Inverse leverage with stake detection
  docs/bot-basics.md
  freqtrade/freqtradebot.py
  freqtrade/optimize/backtesting.py
  tests/test_freqtradebot.py
Labels: Non-spot

#6559 Futures strategy migration docs
  docs/backtesting.md
  docs/bot-basics.md
  docs/configuration.md
  docs/deprecated.md
  docs/faq.md
  docs/hyperopt.md
  docs/leverage.md
  docs/strategy-advanced.md
  docs/strategy-callbacks.md
  docs/strategy-customization.md
  docs/strategy_analysis_example.md
  docs/strategy_migration.md
  freqtrade/strategy/interface.py
  freqtrade/templates/base_strategy.py.j2
  freqtrade/templates/sample_short_strategy.py
  freqtrade/templates/sample_strategy.py
  freqtrade/templates/strategy_analysis_example.ipynb
  mkdocs.yml
Labels: Documentation, Non-spot

#6561 Unified taker and maker's stake amount calculation logic
  freqtrade/freqtradebot.py
  freqtrade/persistence/models.py
  tests/test_freqtradebot.py
  tests/test_persistence.py
Labels: Non-spot

#6560 Inject path to strategy loading
  docs/strategy-advanced.md
  freqtrade/resolvers/iresolver.py
  tests/strategy/strats/hyperoptable_strategy.py
  tests/strategy/strats/strategy_test_v2.py
Labels: Enhancement

#6540 correcting docs for pricing of ask strategy
  docs/includes/pricing.md
Labels: Documentation

#6576 funding_fee tests
  freqtrade/exchange/exchange.py
  freqtrade/freqtradebot.py
  tests/exchange/test_exchange.py
  tests/test_freqtradebot.py
Labels: Non-spot

#6585 Removed old datetime keys and added timestamp
  tests/conftest.py
Labels: Tech maintenance

#6588 Add amount_to_contracts and order_contracts_to_amount to exchange.stoploss
  freqtrade/exchange/exchange.py
  tests/exchange/test_exchange.py
Labels: Non-spot

#6589 Short timeout
  config_examples/config_binance.example.json
  config_examples/config_bittrex.example.json
  config_examples/config_ftx.example.json
  config_examples/config_full.example.json
  config_examples/config_kraken.example.json
  docs/bot-basics.md
  docs/configuration.md
  docs/strategy-callbacks.md
  docs/strategy_migration.md
  freqtrade/configuration/config_validation.py
  freqtrade/constants.py
  freqtrade/freqtradebot.py
  freqtrade/optimize/backtesting.py
  freqtrade/resolvers/strategy_resolver.py
  freqtrade/rpc/api_server/api_schemas.py
  freqtrade/strategy/interface.py
  freqtrade/templates/base_config.json.j2
  freqtrade/templates/subtemplates/strategy_methods_advanced.j2
  tests/conftest.py
  tests/strategy/strats/broken_strats/broken_futures_strategies.py
  tests/strategy/test_strategy_loading.py
  tests/test_configuration.py
  tests/test_freqtradebot.py
Labels: Non-spot

#6590 Fix gateio fee handling for futures
  freqtrade/exchange/exchange.py
  freqtrade/exchange/gateio.py
  freqtrade/freqtradebot.py
  tests/exchange/test_ccxt_compat.py
  tests/exchange/test_exchange.py
  tests/exchange/test_gateio.py
Labels: Non-spot

#6607 Short pricing updates
  config_examples/config_binance.example.json
  config_examples/config_bittrex.example.json
  config_examples/config_ftx.example.json
  config_examples/config_full.example.json
  config_examples/config_kraken.example.json
  docs/bot-basics.md
  docs/configuration.md
  docs/includes/pricing.md
  docs/sandbox-testing.md
  docs/strategy-callbacks.md
  docs/strategy_migration.md
  freqtrade/configuration/config_validation.py
  freqtrade/configuration/configuration.py
  freqtrade/constants.py
  freqtrade/exchange/exchange.py
  freqtrade/freqtradebot.py
  freqtrade/optimize/hyperopt.py
  freqtrade/rpc/api_server/api_schemas.py
  freqtrade/rpc/rpc.py
  freqtrade/rpc/telegram.py
  freqtrade/strategy/interface.py
  freqtrade/templates/base_config.json.j2
  freqtrade/templates/base_strategy.py.j2
  freqtrade/templates/sample_strategy.py
  freqtrade/templates/subtemplates/strategy_methods_advanced.j2
  tests/conftest.py
  tests/exchange/test_ccxt_compat.py
  tests/exchange/test_exchange.py
  tests/rpc/test_rpc_apiserver.py
  tests/test_configuration.py
  tests/test_freqtradebot.py
Labels: Non-spot

#6608 Add few lines to docs
  docs/exchanges.md
  docs/strategy-customization.md
Labels: Non-spot

#6618 Add trading mode to list-pairs and list-markets output in docs
  docs/utils.md
Labels: Documentation, Non-spot
