Repository freqtrade/freqtrade, pull requests merged in 2022-01, with the labels that each got.

#6144 Remove asyncio warnings due to deprecation on 3.10
  freqtrade/exchange/exchange.py
  freqtrade/optimize/hyperopt.py
  freqtrade/rpc/api_server/uvicorn_threaded.py
Labels: Tech maintenance

#6145 Fix CI failures
  .github/workflows/ci.yml
  build_helpers/install_windows.ps1
  requirements.txt
Labels: Tech maintenance

#6147 Plot parallel and underwater
  docs/assets/plot-profit.png
  docs/plotting.md
  freqtrade/data/btanalysis.py
  freqtrade/plot/plotting.py
  tests/data/test_btanalysis.py
  tests/test_plotting.py
Labels: Enhancement, Plotting

#6148 Removed some todo-lev comments
  freqtrade/exchange/bybit.py
  freqtrade/exchange/ftx.py
  freqtrade/freqtradebot.py
  tests/optimize/test_hyperopt.py
  tests/test_freqtradebot.py
  tests/test_persistence.py
Labels: Non-spot

#5888 Convert contract size to underlying asset size
  freqtrade/exchange/exchange.py
  tests/conftest.py
  tests/exchange/test_exchange.py
  tests/exchange/test_kraken.py
Labels: Non-spot

#6168 Futures dust warning
  freqtrade/freqtradebot.py
Labels: Non-spot

#6170 contractSize is a string coming from ccxt
  freqtrade/exchange/exchange.py
  tests/conftest.py
  tests/exchange/test_exchange.py
Labels: Non-spot

#6177 Remove old bt format
  freqtrade/data/btanalysis.py
  tests/data/test_btanalysis.py
  tests/test_plotting.py
  tests/testdata/backtest-result_test.json
Labels: Tech maintenance

#6173 Selectively convert quote to base volume in volumepairlist
  freqtrade/exchange/exchange.py
  freqtrade/exchange/ftx.py
  freqtrade/exchange/gateio.py
  freqtrade/plugins/pairlist/VolumePairList.py
  tests/plugins/test_pairlist.py
Labels: Pairlist

#6181 Simplify optimizereports
  freqtrade/optimize/hyperopt.py
  freqtrade/optimize/optimize_reports.py
  tests/optimize/test_hyperopt.py
  tests/optimize/test_optimize_reports.py
Labels: Backtest, Tech maintenance

#6182 Fix #6179
  freqtrade/optimize/backtesting.py
Labels: Backtest

#6184 Removed rename Todos
  freqtrade/freqtradebot.py
  freqtrade/persistence/migrations.py
  tests/conftest_trades.py
Labels: Non-spot

#6079 Initial position adjustment support (DCA)
  docs/bot-basics.md
  docs/configuration.md
  docs/plotting.md
  docs/strategy-callbacks.md
  freqtrade/freqtradebot.py
  freqtrade/optimize/backtesting.py
  freqtrade/persistence/models.py
  freqtrade/resolvers/strategy_resolver.py
  freqtrade/rpc/rpc.py
  freqtrade/strategy/interface.py
  tests/optimize/test_backtesting_adjust_position.py
  tests/strategy/strats/strategy_test_v2.py
  tests/test_freqtradebot.py
  tests/test_integration.py
  tests/test_persistence.py
Labels: Enhancement

#6172 Backtest result reuse
  docs/backtesting.md
  freqtrade/commands/arguments.py
  freqtrade/commands/cli_options.py
  freqtrade/configuration/configuration.py
  freqtrade/data/btanalysis.py
  freqtrade/misc.py
  freqtrade/optimize/backtesting.py
  freqtrade/optimize/edge_cli.py
  freqtrade/optimize/optimize_reports.py
  tests/optimize/test_backtesting.py
  tests/optimize/test_optimize_reports.py
Labels: Enhancement, Backtest

#6238 Add position adjustment On or Off on startup message
  freqtrade/rpc/rpc_manager.py
Labels: RPC

#6228 Stoploss from open for shorts
  freqtrade/strategy/strategy_helper.py
  tests/strategy/test_strategy_helpers.py
Labels: Non-spot

#6185 cleanup funding fee tests
  freqtrade/persistence/models.py
  tests/test_persistence.py
Labels: Non-spot

#6264 add buy_tag to trade tooltip in plots
  freqtrade/plot/plotting.py
  tests/test_plotting.py
  tests/testdata/backtest-result_new.json
Labels: Plotting

#6259 add "# Buys" column to status table
  freqtrade/rpc/rpc.py
  tests/rpc/test_rpc.py
Labels: RPC

#6274 set stoploss at trade creation
  freqtrade/optimize/backtesting.py
Labels: Backtest

#6275 Extract timedout from ftbot
  docs/strategy-callbacks.md
  freqtrade/freqtradebot.py
  freqtrade/strategy/interface.py
Labels: Tech maintenance

#6282 Fix missing order time data in backtesting.
  freqtrade/optimize/backtesting.py
Labels: Backtest

#6281 Entry callbacks - provide buy_tag
  docs/strategy-callbacks.md
  freqtrade/freqtradebot.py
  freqtrade/optimize/backtesting.py
  freqtrade/strategy/interface.py
  freqtrade/templates/subtemplates/strategy_methods_advanced.j2
  tests/strategy/test_default_strategy.py
Labels: Enhancement

#6276 Add support for shorts in strategy.stoploss_from_absolute()
  docs/strategy-callbacks.md
  docs/strategy-customization.md
  freqtrade/strategy/strategy_helper.py
  tests/strategy/test_strategy_helpers.py
Labels: Non-spot

#6258 Pass dimensions to generate_estimator
  docs/advanced-hyperopt.md
  freqtrade/optimize/hyperopt.py
  freqtrade/optimize/hyperopt_auto.py
  freqtrade/optimize/hyperopt_interface.py
Labels: Hyperopt

#6231 Funding rate backtest
  freqtrade/data/history/idatahandler.py
  freqtrade/exchange/exchange.py
  freqtrade/exchange/kraken.py
  freqtrade/freqtradebot.py
  freqtrade/optimize/backtesting.py
  tests/commands/test_commands.py
  tests/data/test_history.py
  tests/exchange/test_ccxt_compat.py
  tests/exchange/test_exchange.py
  tests/optimize/test_backtesting.py
  tests/test_freqtradebot.py
  tests/testdata/futures/XRP_USDT-8h-funding_rate.json
  tests/testdata/futures/XRP_USDT-8h-mark.json
Labels: Non-spot

#6260 Add max_buy_position_adjustment as attribute
  docs/configuration.md
  docs/strategy-callbacks.md
  freqtrade/constants.py
  freqtrade/freqtradebot.py
  freqtrade/optimize/backtesting.py
  freqtrade/resolvers/strategy_resolver.py
  freqtrade/rpc/api_server/api_schemas.py
  freqtrade/rpc/rpc.py
  freqtrade/rpc/telegram.py
  freqtrade/strategy/interface.py
  tests/test_freqtradebot.py
Labels: Enhancement

#6309 Filter tickers on stake-currency for kraken
  freqtrade/exchange/exchange.py
  freqtrade/exchange/kraken.py
  tests/exchange/test_ccxt_compat.py
Labels: Tech maintenance

#6306 add `/forcelong` and `/forceshort` commands
  docs/rest-api.md
  docs/telegram-usage.md
  freqtrade/enums/signaltype.py
  freqtrade/rpc/api_server/api_schemas.py
  freqtrade/rpc/api_server/api_v1.py
  freqtrade/rpc/rpc.py
  freqtrade/rpc/telegram.py
  scripts/rest_client.py
  tests/rpc/test_rpc.py
  tests/rpc/test_rpc_apiserver.py
  tests/rpc/test_rpc_telegram.py
  tests/test_integration.py
Labels: RPC, Non-spot

#6312 Short informative decorator
  freqtrade/data/dataprovider.py
  freqtrade/strategy/informative_decorator.py
  freqtrade/strategy/interface.py
  tests/strategy/strats/informative_decorator_strategy.py
  tests/strategy/test_strategy_helpers.py
Labels: Non-spot

#6331 Todo-levs
  freqtrade/persistence/models.py
  tests/conftest.py
Labels: Non-spot

#6330 Removed unnecessary CCXT market checks
  freqtrade/exchange/exchange.py
  freqtrade/plugins/pairlist/PriceFilter.py
  tests/conftest.py
  tests/exchange/test_exchange.py
Labels: Non-spot

#6334 Removed PrecisionFilter liquidation price TODO-lev
  freqtrade/plugins/pairlist/PrecisionFilter.py
Labels: Non-spot

#6332 Binance max lev
  freqtrade/exchange/binance.py
  freqtrade/exchange/exchange.py
  tests/exchange/test_binance.py
Labels: Non-spot
