Repository freqtrade/freqtrade, pull requests merged in 2022-02, with the labels that each got.

#5849 Isolated liq
  freqtrade/constants.py
  freqtrade/exchange/binance.py
  freqtrade/exchange/exchange.py
  freqtrade/exchange/gateio.py
  freqtrade/freqtradebot.py
  freqtrade/persistence/models.py
  tests/conftest.py
  tests/exchange/test_binance.py
  tests/exchange/test_exchange.py
  tests/exchange/test_gateio.py
  tests/test_freqtradebot.py
  tests/test_persistence.py
Labels: Non-spot

#6342 Changed name Collateral to MarginMode, and collateral to margin_mode
  docs/configuration.md
  docs/leverage.md
  freqtrade/constants.py
  freqtrade/enums/__init__.py
  freqtrade/enums/marginmode.py
  freqtrade/exchange/binance.py
  freqtrade/exchange/bybit.py
  freqtrade/exchange/exchange.py
  freqtrade/exchange/ftx.py
  freqtrade/exchange/gateio.py
  freqtrade/exchange/kraken.py
  freqtrade/exchange/okex.py
  freqtrade/freqtradebot.py
  tests/conftest.py
  tests/exchange/test_binance.py
  tests/exchange/test_ccxt_compat.py
  tests/exchange/test_exchange.py
  tests/optimize/test_backtesting.py
  tests/test_freqtradebot.py
Labels: Non-spot

#6346 Minor fixes for feat/short
  freqtrade/exchange/binance.py
  freqtrade/exchange/exchange.py
  freqtrade/exchange/ftx.py
  freqtrade/exchange/kraken.py
  freqtrade/exchange/okex.py
  freqtrade/freqtradebot.py
Labels: Non-spot

#6333 New config
  config_examples/config_full.example.json
  freqtrade/commands/build_config_commands.py
  freqtrade/exchange/okex.py
  freqtrade/templates/base_config.json.j2
  tests/commands/test_build_config.py
Labels: Non-spot

#6307 Remove shift in analyzed dataframe columns
  freqtrade/optimize/backtesting.py
  tests/optimize/test_backtesting.py
Labels: Backtest

#6294 /health api and telegram commands to return last processing time
  freqtrade/freqtradebot.py
  freqtrade/rpc/api_server/api_schemas.py
  freqtrade/rpc/api_server/api_v1.py
  freqtrade/rpc/rpc.py
  freqtrade/rpc/telegram.py
  tests/rpc/test_rpc.py
  tests/rpc/test_rpc_apiserver.py
  tests/rpc/test_rpc_telegram.py
Labels: Enhancement, RPC

#6349 Todos
  freqtrade/constants.py
  freqtrade/enums/marginmode.py
  freqtrade/exchange/exchange.py
  freqtrade/freqtradebot.py
  freqtrade/optimize/backtesting.py
  freqtrade/persistence/models.py
  freqtrade/plot/plotting.py
  tests/exchange/test_exchange.py
  tests/exchange/test_kraken.py
  tests/strategy/strats/strategy_test_v3.py
  tests/test_freqtradebot.py
Labels: Non-spot

#6341 Plotting: add alias `--backtest-filename` for `--export-filename`
  docs/plotting.md
  freqtrade/commands/arguments.py
  freqtrade/commands/cli_options.py
  freqtrade/configuration/configuration.py
  freqtrade/plot/plotting.py
Labels: Backtest

#6272 Add more info on Telegram's status message
  freqtrade/persistence/models.py
  freqtrade/rpc/telegram.py
  tests/conftest_trades.py
  tests/rpc/test_rpc.py
  tests/rpc/test_rpc_telegram.py
  tests/test_persistence.py
Labels: Enhancement, RPC

#6354 wrote ccxt_compat.test_get_max_leverage_spot test_get_max_leverage_fu…
  requirements.txt
  setup.py
  tests/exchange/test_ccxt_compat.py
Labels: Non-spot

#6316 exchange.get_max_pair_stake_amount
  freqtrade/exchange/exchange.py
  freqtrade/freqtradebot.py
  freqtrade/optimize/backtesting.py
  freqtrade/wallets.py
  tests/conftest.py
  tests/exchange/test_exchange.py
  tests/optimize/test_backtest_detail.py
  tests/optimize/test_backtesting.py
  tests/optimize/test_backtesting_adjust_position.py
  tests/test_freqtradebot.py
  tests/test_wallets.py
Labels: Non-spot

#6273 Update database migrations for PG and mariadb
  freqtrade/persistence/migrations.py
  tests/test_persistence.py
Labels: Tech maintenance

#6360 Hide some lines for /status when a trade is closed
  freqtrade/rpc/telegram.py
  tests/rpc/test_rpc_telegram.py
Labels: RPC

#6375 deleted outdated todos
  freqtrade/exchange/exchange.py
  tests/optimize/test_backtesting.py
Labels: Non-spot

#6362 Add ProfitDrawdownHyperoptLoss method
  docs/hyperopt.md
  freqtrade/constants.py
  freqtrade/optimize/hyperopt_loss_profit_drawdown.py
  tests/optimize/test_hyperoptloss.py
Labels: Enhancement, Hyperopt

#6235 Backtest order timeout
  docs/backtesting.md
  docs/bot-basics.md
  docs/strategy-callbacks.md
  freqtrade/constants.py
  freqtrade/freqtradebot.py
  freqtrade/optimize/backtesting.py
  freqtrade/optimize/optimize_reports.py
  freqtrade/persistence/models.py
  freqtrade/strategy/interface.py
  freqtrade/wallets.py
  tests/conftest.py
  tests/optimize/__init__.py
  tests/optimize/test_backtest_detail.py
  tests/optimize/test_backtesting.py
  tests/optimize/test_hyperopt.py
  tests/optimize/test_optimize_reports.py
  tests/test_freqtradebot.py
Labels: Backtest

#6340 freqUI: fix can't import backtest with missing datetime data
  freqtrade/rpc/rpc.py
  tests/rpc/test_rpc_apiserver.py
Labels: RPC, freqUI

#6385 binance futures stoploss
  freqtrade/exchange/binance.py
Labels: Non-spot

#6391 feature: add buy tag to forcebuy
  freqtrade/rpc/api_server/api_schemas.py
  freqtrade/rpc/api_server/api_v1.py
  freqtrade/rpc/rpc.py
Labels: RPC

#6386 Added liquidation_buffer to freqtradebot
  docs/configuration.md
  docs/leverage.md
  freqtrade/constants.py
  freqtrade/exchange/exchange.py
  freqtrade/freqtradebot.py
  tests/exchange/test_exchange.py
  tests/test_freqtradebot.py
Labels: Non-spot

#6394 todo removal
  freqtrade/edge/edge_positioning.py
  freqtrade/plugins/protections/stoploss_guard.py
Labels: Non-spot

#6397 edited todo-lev comments
  freqtrade/commands/data_commands.py
  freqtrade/enums/candletype.py
  freqtrade/exchange/exchange.py
  freqtrade/freqtradebot.py
  freqtrade/optimize/backtesting.py
  freqtrade/templates/sample_short_strategy.py
  tests/optimize/test_backtest_detail.py
  tests/strategy/strats/strategy_test_v3.py
Labels: Non-spot

#6417 Attempt fix for #6261
  freqtrade/optimize/backtesting.py
  tests/optimize/test_backtest_detail.py
Labels: Backtest

#6373 Leverage tiers
  freqtrade/exchange/binance.py
  freqtrade/exchange/binance_leverage_brackets.json
  freqtrade/exchange/binance_leverage_tiers.json
  freqtrade/exchange/exchange.py
  freqtrade/exchange/gateio.py
  freqtrade/exchange/okx.py
  requirements.txt
  setup.py
  tests/commands/test_commands.py
  tests/conftest.py
  tests/exchange/test_binance.py
  tests/exchange/test_ccxt_compat.py
  tests/exchange/test_exchange.py
  tests/exchange/test_gateio.py
  tests/exchange/test_okx.py
  tests/optimize/test_hyperopt.py
  tests/test_freqtradebot.py
Labels: Non-spot

#6425 leverage in trade.stake_amount calculation
  freqtrade/freqtradebot.py
  tests/test_freqtradebot.py
Labels: Non-spot

#6437 Migrate trade updating to use order model
  freqtrade/freqtradebot.py
  freqtrade/persistence/migrations.py
  freqtrade/persistence/models.py
  tests/conftest.py
  tests/rpc/test_rpc.py
  tests/rpc/test_rpc_telegram.py
  tests/test_freqtradebot.py
  tests/test_integration.py
  tests/test_persistence.py
Labels: Tech maintenance

#6416 Update windows_installation.md
  docs/assets/windows_install.png
  docs/windows_installation.md
Labels: Documentation

#6440 Add leverage strategy to new-strategy command
  freqtrade/strategy/interface.py
  freqtrade/templates/base_strategy.py.j2
  freqtrade/templates/subtemplates/strategy_methods_advanced.j2
Labels: Non-spot

#6463 Stoploss simplify - kucoin stoploss on exchange
  docs/exchanges.md
  docs/stoploss.md
  freqtrade/exchange/binance.py
  freqtrade/exchange/exchange.py
  freqtrade/exchange/ftx.py
  freqtrade/exchange/kraken.py
  freqtrade/exchange/kucoin.py
  freqtrade/freqtradebot.py
  tests/exchange/test_kucoin.py
Labels: Enhancement, Stoploss

#6465 Huobi
  README.md
  docs/exchanges.md
  docs/index.md
  docs/stoploss.md
  freqtrade/commands/build_config_commands.py
  freqtrade/exchange/__init__.py
  freqtrade/exchange/exchange.py
  freqtrade/exchange/huobi.py
  freqtrade/templates/subtemplates/exchange_huobi.j2
  requirements.txt
  setup.py
  tests/exchange/test_exchange.py
  tests/exchange/test_huobi.py
Labels: Enhancement

#6423 Futures wallet amount
  freqtrade/exchange/exchange.py
  freqtrade/freqtradebot.py
  freqtrade/persistence/models.py
  freqtrade/rpc/api_server/api_schemas.py
  freqtrade/rpc/rpc.py
  freqtrade/rpc/telegram.py
  freqtrade/wallets.py
  tests/exchange/test_exchange.py
  tests/rpc/test_rpc.py
  tests/rpc/test_rpc_apiserver.py
  tests/rpc/test_rpc_telegram.py
  tests/test_persistence.py
  tests/test_wallets.py
Labels: Non-spot

#6456 Lev tier update
  freqtrade/exchange/exchange.py
  freqtrade/exchange/gateio.py
  freqtrade/exchange/okx.py
  requirements.txt
  tests/exchange/test_ccxt_compat.py
  tests/exchange/test_gateio.py
  tests/exchange/test_okx.py
Labels: Non-spot

#6466 Leverage stoploss
  freqtrade/freqtradebot.py
  freqtrade/persistence/models.py
  tests/optimize/test_backtest_detail.py
  tests/test_persistence.py
Labels: Non-spot

#6400 trade-adjustment for short trades
  docs/strategy-callbacks.md
  freqtrade/freqtradebot.py
  freqtrade/optimize/backtesting.py
  freqtrade/persistence/models.py
  freqtrade/rpc/rpc.py
  tests/strategy/strats/strategy_test_v3.py
  tests/test_integration.py
  tests/test_persistence.py
Labels: Non-spot
