Repository freqtrade/freqtrade, pull requests merged in 2022-04, with the labels that each got.

#6622 Short plot
  docs/plotting.md
  freqtrade/plot/plotting.py
  freqtrade/rpc/rpc.py
  tests/test_plotting.py
Labels: Non-spot

#6624 docs for shorting
  docs/leverage.md
  docs/strategy-customization.md
Labels: Documentation, Non-spot

#6632 Short terminology
  docs/advanced-hyperopt.md
  docs/sql_cheatsheet.md
  docs/strategy-customization.md
  docs/strategy_analysis_example.md
  docs/strategy_migration.md
  docs/telegram-usage.md
  docs/webhook-config.md
  freqtrade/data/btanalysis.py
  freqtrade/freqtradebot.py
  freqtrade/optimize/backtesting.py
  freqtrade/optimize/optimize_reports.py
  freqtrade/persistence/migrations.py
  freqtrade/persistence/models.py
  freqtrade/plot/plotting.py
  freqtrade/plugins/protections/stoploss_guard.py
  freqtrade/rpc/api_server/api_schemas.py
  freqtrade/rpc/rpc.py
  freqtrade/rpc/telegram.py
  freqtrade/templates/strategy_analysis_example.ipynb
  tests/conftest_trades.py
  tests/conftest_trades_usdt.py
  tests/edge/test_edge.py
  tests/optimize/__init__.py
  tests/optimize/conftest.py
  tests/optimize/test_backtest_detail.py
  tests/optimize/test_backtesting.py
  tests/optimize/test_backtesting_adjust_position.py
  tests/optimize/test_hyperopt.py
  tests/optimize/test_optimize_reports.py
  tests/plugins/test_protections.py
  tests/rpc/test_rpc.py
  tests/rpc/test_rpc_apiserver.py
  tests/rpc/test_rpc_telegram.py
  tests/test_freqtradebot.py
  tests/test_integration.py
  tests/test_persistence.py
  tests/testdata/backtest-result_multistrat.json
  tests/testdata/backtest-result_new.json
Labels: Non-spot

#6648 Exit type rename
  config_examples/config_full.example.json
  docs/backtesting.md
  docs/configuration.md
  docs/deprecated.md
  docs/sql_cheatsheet.md
  docs/strategy-callbacks.md
  docs/strategy_migration.md
  docs/telegram-usage.md
  docs/webhook-config.md
  freqtrade/configuration/deprecated_settings.py
  freqtrade/constants.py
  freqtrade/edge/edge_positioning.py
  freqtrade/enums/exittype.py
  freqtrade/enums/rpcmessagetype.py
  freqtrade/freqtradebot.py
  freqtrade/optimize/backtesting.py
  freqtrade/persistence/migrations.py
  freqtrade/rpc/rpc.py
  freqtrade/rpc/telegram.py
  freqtrade/rpc/webhook.py
  freqtrade/strategy/interface.py
  freqtrade/templates/subtemplates/strategy_methods_advanced.j2
  tests/edge/test_edge.py
  tests/optimize/test_backtest_detail.py
  tests/optimize/test_hyperopt.py
  tests/optimize/test_optimize_reports.py
  tests/plugins/test_protections.py
  tests/rpc/test_rpc_telegram.py
  tests/rpc/test_rpc_webhook.py
  tests/strategy/test_interface.py
  tests/test_freqtradebot.py
  tests/test_integration.py
  tests/testdata/backtest-result_multistrat.json
  tests/testdata/backtest-result_new.json
Labels: Non-spot

#6658 renamed enter-side
  docs/strategy-callbacks.md
  docs/strategy_migration.md
  freqtrade/freqtradebot.py
  freqtrade/optimize/backtesting.py
  freqtrade/persistence/models.py
  freqtrade/rpc/rpc.py
  freqtrade/rpc/telegram.py
  freqtrade/strategy/interface.py
  tests/conftest_trades.py
  tests/strategy/strats/strategy_test_v3.py
  tests/test_freqtradebot.py
  tests/test_persistence.py
Labels: Non-spot

#6656 Use sell signal -> use_exit_signal
  config_examples/config_full.example.json
  docs/configuration.md
  docs/strategy-callbacks.md
  docs/strategy-customization.md
  docs/strategy_migration.md
  freqtrade/configuration/config_validation.py
  freqtrade/configuration/deprecated_settings.py
  freqtrade/constants.py
  freqtrade/freqtradebot.py
  freqtrade/optimize/hyperopt.py
  freqtrade/optimize/optimize_reports.py
  freqtrade/resolvers/strategy_resolver.py
  freqtrade/strategy/interface.py
  freqtrade/templates/base_strategy.py.j2
  freqtrade/templates/sample_strategy.py
  tests/optimize/test_backtest_detail.py
  tests/optimize/test_backtesting.py
  tests/optimize/test_backtesting_adjust_position.py
  tests/strategy/strats/strategy_test_v2.py
  tests/strategy/test_strategy_loading.py
  tests/test_configuration.py
  tests/test_freqtradebot.py
  tests/testdata/backtest-result_multistrat.json
  tests/testdata/backtest-result_new.json
  tests/testdata/strategy_SampleStrategy.fthypt
Labels: Non-spot

#6653 renamed forceentry forceexit
  README.md
  config_examples/config_full.example.json
  docs/backtesting.md
  docs/configuration.md
  docs/rest-api.md
  docs/sql_cheatsheet.md
  docs/stoploss.md
  docs/strategy_migration.md
  docs/telegram-usage.md
  freqtrade/configuration/config_validation.py
  freqtrade/constants.py
  freqtrade/freqtradebot.py
  freqtrade/rpc/api_server/api_schemas.py
  freqtrade/rpc/api_server/api_v1.py
  freqtrade/rpc/rpc.py
  freqtrade/rpc/telegram.py
  freqtrade/templates/subtemplates/exchange_bittrex.j2
  scripts/rest_client.py
  tests/rpc/test_rpc.py
  tests/rpc/test_rpc_apiserver.py
  tests/rpc/test_rpc_telegram.py
  tests/test_configuration.py
Labels: Non-spot

#6636 added pre-commit
  .pre-commit-config.yaml
  docs/developer.md
  requirements-dev.txt
  setup.sh
Labels: Tech maintenance

#6665 Allow recursive loading of configuration files
  config_examples/config_full.example.json
  docs/configuration.md
  freqtrade/configuration/load_config.py
  freqtrade/constants.py
  tests/test_configuration.py
  tests/testdata/testconfigs/recursive.json
  tests/testdata/testconfigs/test_base_config.json
  tests/testdata/testconfigs/test_pricing2_conf.json
  tests/testdata/testconfigs/test_pricing_conf.json
  tests/testdata/testconfigs/testconfig.json
Labels: Enhancement

#6670 store base and quote currency separately in the database
  freqtrade/exchange/exchange.py
  freqtrade/freqtradebot.py
  freqtrade/optimize/backtesting.py
  freqtrade/persistence/migrations.py
  freqtrade/persistence/models.py
  freqtrade/rpc/api_server/api_schemas.py
  freqtrade/rpc/rpc.py
  freqtrade/rpc/telegram.py
  tests/rpc/test_rpc.py
  tests/rpc/test_rpc_apiserver.py
  tests/rpc/test_rpc_telegram.py
  tests/test_persistence.py
Labels: RPC

#6671 Custom exit - call it independent of profit
  docs/strategy-callbacks.md
  docs/strategy_migration.md
  freqtrade/strategy/interface.py
  tests/strategy/test_interface.py
  tests/test_freqtradebot.py
Labels: Enhancement

#6615 Add selection buttons for trades to forcesell cmd in telegram
  docs/telegram-usage.md
  freqtrade/rpc/telegram.py
  tests/rpc/test_rpc_telegram.py
Labels: Enhancement, RPC

#6685 Backtesting load history
  freqtrade/data/btanalysis.py
  freqtrade/rpc/api_server/api_backtest.py
  freqtrade/rpc/api_server/api_schemas.py
  freqtrade/rpc/api_server/api_v1.py
  tests/commands/test_commands.py
  tests/data/test_btanalysis.py
  tests/optimize/test_optimize_reports.py
  tests/rpc/test_rpc_apiserver.py
  tests/test_plotting.py
  tests/testdata/backtest_results/.last_result.json
  tests/testdata/backtest_results/backtest-result_multistrat.json
  tests/testdata/backtest_results/backtest-result_multistrat.meta.json
  tests/testdata/backtest_results/backtest-result_new.json
  tests/testdata/backtest_results/backtest-result_new.meta.json
Labels: Enhancement, RPC

#6694 switch notionalFloor -> minNotional and notionalCap -> maxNotional
  freqtrade/exchange/binance_leverage_tiers.json
  freqtrade/exchange/exchange.py
  requirements.txt
  setup.py
  tests/exchange/test_binance.py
  tests/exchange/test_ccxt_compat.py
  tests/exchange/test_exchange.py
  tests/exchange/test_okx.py
Labels: CCXT, Non-spot

#6563 Optimize only new points
  freqtrade/optimize/hyperopt.py
  freqtrade/optimize/hyperopt_tools.py
  tests/conftest.py
  tests/optimize/test_hyperopt.py
Labels: Hyperopt

#6543 Add support for storing buy candle indicator rows in backtesting results
  docs/advanced-backtesting.md
  docs/backtesting.md
  docs/configuration.md
  docs/data-analysis.md
  docs/strategy_analysis_example.md
  freqtrade/constants.py
  freqtrade/misc.py
  freqtrade/optimize/backtesting.py
  freqtrade/optimize/optimize_reports.py
  mkdocs.yml
  tests/optimize/test_backtesting.py
  tests/optimize/test_optimize_reports.py
Labels: Backtest

#6558 Recursively search subdirectories in config['user_data_dir']/strategies for a strategy
  config_examples/config_full.example.json
  docs/configuration.md
  freqtrade/commands/arguments.py
  freqtrade/commands/cli_options.py
  freqtrade/commands/list_commands.py
  freqtrade/configuration/configuration.py
  freqtrade/optimize/hyperopt_tools.py
  freqtrade/resolvers/iresolver.py
  freqtrade/resolvers/strategy_resolver.py
  freqtrade/rpc/api_server/api_v1.py
  tests/commands/test_commands.py
Labels: Enhancement

#6712 Speed up ci by running coverage only where necessary
  .github/workflows/ci.yml
Labels: Tech maintenance

#6723 Strategy v1 remove
  freqtrade/resolvers/strategy_resolver.py
  freqtrade/strategy/interface.py
  tests/commands/test_commands.py
  tests/optimize/test_backtesting.py
  tests/rpc/test_rpc_apiserver.py
  tests/strategy/strats/broken_strats/legacy_strategy_v1.py
  tests/strategy/strats/legacy_strategy_v1.py
  tests/strategy/strats/strategy_test_v2.py
  tests/strategy/test_interface.py
  tests/strategy/test_strategy_loading.py
Labels: Tech maintenance

#6724 Check pre-commit verison updates
  .github/workflows/ci.yml
  .pre-commit-config.yaml
  build_helpers/pre_commit_update.py
  freqtrade/strategy/informative_decorator.py
  freqtrade/strategy/interface.py
  requirements-dev.txt
  setup.cfg
Labels: Tech maintenance

#6725 Add CAGR calculation to backtesting
  docs/backtesting.md
  freqtrade/data/btanalysis.py
  freqtrade/optimize/optimize_reports.py
  tests/data/test_btanalysis.py
Labels: Enhancement, Backtest

#6729 Add 'exit_tag' parameter to 'custom_exit_price' callback.
  docs/strategy-callbacks.md
  freqtrade/freqtradebot.py
  freqtrade/optimize/backtesting.py
  freqtrade/strategy/interface.py
  freqtrade/templates/subtemplates/strategy_methods_advanced.j2
  tests/test_freqtradebot.py
Labels: Enhancement

#6732 Don't call interest_rate and isolated_liq twice
  freqtrade/exchange/exchange.py
  freqtrade/freqtradebot.py
  tests/test_freqtradebot.py
Labels: Non-spot

#6627 Added bot_start callback to strategy interface
  docs/strategy-callbacks.md
  freqtrade/freqtradebot.py
  freqtrade/optimize/backtesting.py
  freqtrade/optimize/edge_cli.py
  freqtrade/plot/plotting.py
  freqtrade/strategy/interface.py
  tests/optimize/test_backtesting.py
  tests/optimize/test_edge_cli.py
  tests/strategy/strats/strategy_test_v3.py
Labels: Enhancement
