Repository freqtrade/freqtrade, pull requests merged in 2022-07, with the labels that each got.

#7051 Gateio fee fix
  freqtrade/exchange/exchange.py
  freqtrade/exchange/gateio.py
  freqtrade/exchange/okx.py
  freqtrade/freqtradebot.py
  freqtrade/persistence/trade_model.py
  requirements.txt
  tests/exchange/test_exchange.py
Labels: Bug

#7092 hyperopt inherit fix
  freqtrade/exchange/exchange.py
  freqtrade/optimize/hyperopt.py
  tests/conftest.py
  tests/optimize/test_hyperopt.py
Labels: Hyperopt

#7093 gateio futures - several fixes
  freqtrade/exchange/exchange.py
  freqtrade/exchange/gateio.py
  freqtrade/freqtradebot.py
  tests/exchange/test_exchange.py
  tests/exchange/test_gateio.py
Labels: Bug

#6780 Dry run taker or maker fees
  freqtrade/constants.py
  freqtrade/exchange/exchange.py
  tests/exchange/test_exchange.py
Labels: Enhancement

#7118 Reenable Catboost test
  tests/freqai/conftest.py
  tests/freqai/test_freqai_datakitchen.py
  tests/freqai/test_freqai_interface.py
Labels: freqAI

#7135 Strategy allow rpc messages
  docs/strategy-customization.md
  docs/telegram-usage.md
  freqtrade/constants.py
  freqtrade/data/dataprovider.py
  freqtrade/enums/rpcmessagetype.py
  freqtrade/freqtradebot.py
  freqtrade/rpc/rpc_manager.py
  freqtrade/rpc/telegram.py
  tests/data/test_dataprovider.py
  tests/rpc/test_rpc_manager.py
  tests/rpc/test_rpc_telegram.py
  tests/test_freqtradebot.py
Labels: Enhancement, RPC

#6545 Partial exit using average price
  docs/strategy-callbacks.md
  freqtrade/enums/exittype.py
  freqtrade/exchange/exchange.py
  freqtrade/freqtradebot.py
  freqtrade/optimize/backtesting.py
  freqtrade/persistence/migrations.py
  freqtrade/persistence/trade_model.py
  freqtrade/rpc/rpc.py
  freqtrade/rpc/telegram.py
  freqtrade/strategy/interface.py
  freqtrade/templates/subtemplates/strategy_methods_advanced.j2
  tests/conftest.py
  tests/exchange/test_exchange.py
  tests/optimize/test_backtesting_adjust_position.py
  tests/rpc/test_rpc.py
  tests/rpc/test_rpc_telegram.py
  tests/strategy/strats/strategy_test_v3.py
  tests/test_freqtradebot.py
  tests/test_integration.py
  tests/test_persistence.py
Labels: Enhancement
