Repository freqtrade/freqtrade, pull requests merged in 2022-05, with the labels that each got.

#6753 Download prepend
  docs/data-download.md
  freqtrade/commands/arguments.py
  freqtrade/commands/cli_options.py
  freqtrade/commands/data_commands.py
  freqtrade/configuration/configuration.py
  freqtrade/data/history/history_utils.py
  freqtrade/exchange/binance.py
  freqtrade/exchange/exchange.py
  tests/data/test_history.py
  tests/exchange/test_exchange.py
Labels: Enhancement, Data download

#6716 Pairlocks direction
  docs/developer.md
  docs/includes/protections.md
  freqtrade/freqtradebot.py
  freqtrade/optimize/backtesting.py
  freqtrade/persistence/migrations.py
  freqtrade/persistence/models.py
  freqtrade/persistence/pairlock_middleware.py
  freqtrade/plugins/protectionmanager.py
  freqtrade/plugins/protections/cooldown_period.py
  freqtrade/plugins/protections/iprotection.py
  freqtrade/plugins/protections/low_profit_pairs.py
  freqtrade/plugins/protections/max_drawdown_protection.py
  freqtrade/plugins/protections/stoploss_guard.py
  freqtrade/rpc/api_server/api_schemas.py
  freqtrade/strategy/interface.py
  tests/plugins/test_pairlocks.py
  tests/plugins/test_protections.py
  tests/strategy/test_interface.py
  tests/test_freqtradebot.py
  tests/test_persistence.py
Labels: Enhancement, Non-spot

#6715 Add relative drawdown
  docs/backtesting.md
  docs/hyperopt.md
  freqtrade/constants.py
  freqtrade/data/metrics.py
  freqtrade/optimize/hyperopt_loss/hyperopt_loss_max_drawdown_relative.py
  freqtrade/optimize/hyperopt_loss_interface.py
  freqtrade/optimize/optimize_reports.py
  freqtrade/plot/plotting.py
  tests/data/test_btanalysis.py
  tests/optimize/test_hyperoptloss.py
  tests/test_plotting.py
Labels: Enhancement

#6777 Fix fee handling for futures trades
  freqtrade/exchange/exchange.py
  tests/exchange/test_exchange.py
Labels: Non-spot

#6789 Okx positionmode
  docs/exchanges.md
  freqtrade/exchange/exchange.py
  freqtrade/exchange/ftx.py
  freqtrade/exchange/kraken.py
  freqtrade/exchange/okx.py
  tests/exchange/test_ccxt_compat.py
  tests/exchange/test_exchange.py
  tests/exchange/test_okx.py
Labels: Non-spot

#6692 Feature: Readjust Entry Order
  docs/bot-basics.md
  docs/strategy-callbacks.md
  freqtrade/constants.py
  freqtrade/freqtradebot.py
  freqtrade/optimize/backtesting.py
  freqtrade/persistence/models.py
  freqtrade/strategy/interface.py
  freqtrade/templates/base_strategy.py.j2
  freqtrade/templates/subtemplates/strategy_methods_advanced.j2
  tests/optimize/__init__.py
  tests/optimize/test_backtest_detail.py
  tests/test_freqtradebot.py
  tests/test_integration.py
Labels: Enhancement

#6790 Report profit only on filled entries.
  freqtrade/rpc/rpc.py
  tests/rpc/test_rpc.py
Labels: RPC

#6797 then -> than
  docs/includes/pairlists.md
Labels: Documentation

#6812 Db migrate
  docs/utils.md
  freqtrade/commands/__init__.py
  freqtrade/commands/arguments.py
  freqtrade/commands/cli_options.py
  freqtrade/commands/db_commands.py
  freqtrade/configuration/configuration.py
  freqtrade/persistence/migrations.py
  tests/commands/test_commands.py
  tests/test_persistence.py
Labels: Enhancement

#6833 Python 310 main version
  .github/workflows/ci.yml
  Dockerfile
  docker/Dockerfile.armhf
  setup.cfg
  setup.sh
Labels: Tech maintenance

#6851 BT: Reporting canceled trade entries
  docs/backtesting.md
  freqtrade/optimize/backtesting.py
  freqtrade/optimize/optimize_reports.py
  tests/optimize/test_backtesting.py
  tests/optimize/test_hyperopt.py
  tests/optimize/test_optimize_reports.py
Labels: Enhancement

#6848 Datahandler case insensitive
  freqtrade/data/history/hdf5datahandler.py
  freqtrade/data/history/idatahandler.py
  freqtrade/data/history/jsondatahandler.py
  tests/data/test_history.py
Labels: Data download

#6866 Dry orders from db
  docs/configuration.md
  freqtrade/commands/db_commands.py
  freqtrade/commands/list_commands.py
  freqtrade/data/btanalysis.py
  freqtrade/exchange/exchange.py
  freqtrade/freqtradebot.py
  freqtrade/persistence/__init__.py
  freqtrade/persistence/models.py
  freqtrade/persistence/trade_model.py
  tests/commands/test_commands.py
  tests/conftest.py
  tests/exchange/test_exchange.py
  tests/exchange/test_ftx.py
  tests/exchange/test_gateio.py
  tests/test_freqtradebot.py
  tests/test_persistence.py
Labels: Enhancement

#6869 Update leveraged tiers
  docs/developer.md
  freqtrade/exchange/binance_leverage_tiers.json
  tests/exchange/test_binance.py
Labels: Tech maintenance, Non-spot

#6857 Add support for fudging unavailable funding rates, allowing backtesti…
  docs/configuration.md
  docs/leverage.md
  freqtrade/data/history/history_utils.py
  freqtrade/exchange/exchange.py
  freqtrade/optimize/backtesting.py
  tests/exchange/test_exchange.py
Labels: Enhancement, Backtest

#6870 Should exit list
  docs/backtesting.md
  docs/strategy-callbacks.md
  freqtrade/enums/exitchecktuple.py
  freqtrade/freqtradebot.py
  freqtrade/optimize/backtesting.py
  freqtrade/strategy/interface.py
  tests/strategy/test_interface.py
  tests/test_integration.py
Labels: Enhancement

#6887 Run CI against strategy templates
  .github/workflows/ci.yml
Labels: Tech maintenance
