Repository freqtrade/freqtrade, pull requests merged in 2023-08, with the labels that each got.

#8997 add second alternatives instead of using .range
  docs/hyperopt.md
Labels: Documentation

#9013 Add backtest notes capability
  freqtrade/data/btanalysis.py
  freqtrade/optimize/optimize_reports/bt_storage.py
  freqtrade/rpc/api_server/api_backtest.py
  freqtrade/rpc/api_server/api_schemas.py
  freqtrade/rpc/api_server/api_v1.py
  freqtrade/types/backtest_result_type.py
  tests/rpc/test_rpc_apiserver.py
Labels: Enhancement

#9027 Remove sandbox
  config_examples/config_full.example.json
  docs/configuration.md
  docs/sandbox-testing.md
  freqtrade/constants.py
  freqtrade/exchange/exchange.py
  mkdocs.yml
  tests/exchange/test_exchange.py
  tests/test_configuration.py
Labels: Tech maintenance

#9032 Online test refactor
  tests/exchange_online/__init__.py
  tests/exchange_online/conftest.py
  tests/exchange_online/test_ccxt_compat.py
Labels: Tech maintenance

#8903 Freqai pytorch bugfixes
  docs/freqai-parameter-table.md
  freqtrade/freqai/prediction_models/PyTorchMLPClassifier.py
  freqtrade/freqai/prediction_models/PyTorchMLPRegressor.py
  freqtrade/freqai/prediction_models/PyTorchTransformerRegressor.py
  freqtrade/freqai/torch/PyTorchDataConvertor.py
  freqtrade/freqai/torch/PyTorchModelTrainer.py
  tests/freqai/conftest.py
Labels: freqAI

#9061 improve `get_analyzed_dataframe` behavior in early candles
  freqtrade/data/dataprovider.py
  freqtrade/optimize/backtesting.py
  tests/data/test_dataprovider.py
  tests/optimize/test_backtesting.py
Labels: Backtest

#9064 Update setup.sh script to use `.venv`
  build_helpers/install_ta-lib.sh
  docs/bot-usage.md
  docs/data-analysis.md
  docs/faq.md
  docs/hyperopt.md
  docs/installation.md
  docs/windows_installation.md
  pyproject.toml
  setup.sh
Labels: Install, Tech maintenance

#9065 Improve Trades data handling
  freqtrade/commands/cli_options.py
  freqtrade/constants.py
  freqtrade/data/converter.py
  freqtrade/data/history/featherdatahandler.py
  freqtrade/data/history/hdf5datahandler.py
  freqtrade/data/history/history_utils.py
  freqtrade/data/history/idatahandler.py
  freqtrade/data/history/jsondatahandler.py
  freqtrade/data/history/parquetdatahandler.py
  tests/conftest.py
  tests/data/test_converter.py
  tests/data/test_datahandler.py
  tests/data/test_history.py
  tests/testdata/XRP_ETH-trades.parquet
Labels: Enhancement

#9071 improve installation of ta-lib on windows
  build_helpers/install_windows.ps1
Labels: Python, Tech maintenance

#9072 Talib update to 0.4.28
  build_helpers/TA_Lib-0.4.27-cp310-cp310-win_amd64.whl
  build_helpers/TA_Lib-0.4.27-cp311-cp311-win_amd64.whl
  build_helpers/TA_Lib-0.4.27-cp38-cp38-win_amd64.whl
  build_helpers/TA_Lib-0.4.27-cp39-cp39-win_amd64.whl
  build_helpers/TA_Lib-0.4.28-cp310-cp310-win_amd64.whl
  build_helpers/TA_Lib-0.4.28-cp311-cp311-win_amd64.whl
  build_helpers/TA_Lib-0.4.28-cp38-cp38-win_amd64.whl
  build_helpers/TA_Lib-0.4.28-cp39-cp39-win_amd64.whl
  requirements.txt
Labels: Dependencies, Python

#9105 Convert add_state_info warning into a OperationalException
  freqtrade/freqai/RL/BaseEnvironment.py
Labels: freqAI

#9123 Add note about Edge status
  docs/edge.md
Labels: Documentation, Tech maintenance

#9057 "After order" stoploss adjustment
  docs/strategy-callbacks.md
  docs/strategy-customization.md
  docs/strategy_migration.md
  freqtrade/freqtradebot.py
  freqtrade/optimize/backtesting.py
  freqtrade/persistence/migrations.py
  freqtrade/persistence/trade_model.py
  freqtrade/resolvers/strategy_resolver.py
  freqtrade/strategy/interface.py
  freqtrade/templates/strategy_subtemplates/strategy_methods_advanced.j2
  tests/persistence/test_persistence.py
  tests/strategy/test_default_strategy.py
Labels: Enhancement, Stoploss
