Repository freqtrade/freqtrade, pull requests merged in 2023-11, with the labels that each got.

#9369 informative assets -> {base}
  docs/strategy-customization.md
  freqtrade/strategy/informative_decorator.py
  freqtrade/strategy/interface.py
  tests/strategy/strats/informative_decorator_strategy.py
  tests/strategy/test_strategy_helpers.py
Labels: Enhancement

#9375 Update Dockerfile.armhf to use prebuilt wheels
  build_helpers/TA_Lib-0.4.28-cp311-cp311-linux_armv7l.whl
  build_helpers/TA_Lib-0.4.28-cp39-cp39-linux_armv7l.whl
  docker/Dockerfile.armhf
Labels: Tech maintenance

#9378 Bugfix: PyTorchTransformer
  freqtrade/freqai/prediction_models/PyTorchTransformerRegressor.py
Labels: Bug, freqAI

#9382 Reduce wait for ws test
  tests/rpc/test_rpc_apiserver.py
Labels: Tech maintenance

#9407 add entries, exits, and mix_tags API endpoints
  docs/rest-api.md
  freqtrade/rpc/api_server/api_schemas.py
  freqtrade/rpc/api_server/api_v1.py
  scripts/rest_client.py
  tests/rpc/test_rpc_apiserver.py
Labels: Enhancement, RPC

#9451 Remove dependency on blosc
  requirements.txt
Labels: Tech maintenance

#9458 Improve hyperopt Tests
  tests/optimize/test_hyperopt.py
Labels: Tech maintenance

#9469 Update various docker images
  Dockerfile
  docker/Dockerfile.armhf
Labels: Dependencies, Docker

#9436 Remove order list from /status, and add new /order command
  docs/telegram-usage.md
  freqtrade/rpc/telegram.py
  tests/rpc/test_rpc_telegram.py
Labels: RPC
