Repository freqtrade/freqtrade, pull requests merged in 2023-03, with the labels that each got.

#8225 Ruff - add PTH rule and subsequent changes
  freqtrade/configuration/load_config.py
  freqtrade/data/entryexitanalysis.py
  freqtrade/exchange/binance.py
  freqtrade/freqai/data_drawer.py
  freqtrade/freqai/utils.py
  freqtrade/misc.py
  freqtrade/optimize/backtest_caching.py
  freqtrade/plugins/pairlist/RemotePairList.py
  pyproject.toml
  tests/data/test_history.py
  tests/optimize/test_optimize_reports.py
  tests/test_configuration.py
  tests/test_misc.py
Labels: Tech maintenance

#8264 Sqlalchemy 2
  .pre-commit-config.yaml
  build_helpers/pre_commit_update.py
  freqtrade/data/btanalysis.py
  freqtrade/freqtradebot.py
  freqtrade/optimize/backtesting.py
  freqtrade/persistence/base.py
  freqtrade/persistence/models.py
  freqtrade/persistence/pairlock.py
  freqtrade/persistence/pairlock_middleware.py
  freqtrade/persistence/trade_model.py
  freqtrade/rpc/rpc.py
  freqtrade/rpc/telegram.py
  pyproject.toml
  requirements.txt
  tests/persistence/test_persistence.py
  tests/strategy/strats/broken_strats/broken_futures_strategies.py
  tests/strategy/strats/strategy_test_v3.py
  tests/test_freqtradebot.py
Labels: Dependencies, Tech maintenance

#8220 removed redundant dependencies from environment.yml
  docs/installation.md
  environment.yml
Labels: Dependencies

#8267 Python 3.11
  .github/workflows/ci.yml
  docs/freqai.md
  docs/windows_installation.md
  requirements-freqai-rl.txt
  requirements-freqai.txt
  setup.cfg
  tests/freqai/test_freqai_interface.py
  tests/rpc/test_rpc_apiserver.py
  tests/rpc/test_rpc_telegram.py
Labels: Tech maintenance

#8202 remove populate_any_indicators
  freqtrade/freqai/data_kitchen.py
  freqtrade/freqai/freqai_interface.py
  freqtrade/optimize/backtesting.py
  tests/freqai/test_freqai_backtesting.py
  tests/strategy/test_interface.py
Labels: freqAI

#8291 allow user to drop ohlc from features in RL
  docs/freqai-parameter-table.md
  docs/freqai-reinforcement-learning.md
  freqtrade/constants.py
  freqtrade/freqai/RL/BaseReinforcementLearningModel.py
  tests/freqai/conftest.py
  tests/freqai/test_freqai_interface.py
Labels: freqAI

#8273 Stop from open lev
  docs/strategy-callbacks.md
  docs/strategy-customization.md
  freqtrade/strategy/strategy_helper.py
  tests/strategy/test_strategy_helpers.py
Labels: WIP

#8307 Improve tensorboard_log
  docs/freqai-reinforcement-learning.md
  freqtrade/freqai/RL/Base3ActionRLEnv.py
  freqtrade/freqai/RL/Base4ActionRLEnv.py
  freqtrade/freqai/RL/Base5ActionRLEnv.py
  freqtrade/freqai/RL/BaseEnvironment.py
  freqtrade/freqai/RL/TensorboardCallback.py
  freqtrade/freqai/prediction_models/ReinforcementLearner.py
Labels: freqAI

#8340 remove Sqlalchemy .query usage
  freqtrade/commands/db_commands.py
  freqtrade/data/btanalysis.py
  freqtrade/freqtradebot.py
  freqtrade/persistence/models.py
  freqtrade/persistence/pairlock.py
  freqtrade/persistence/pairlock_middleware.py
  freqtrade/persistence/trade_model.py
  freqtrade/rpc/rpc.py
  freqtrade/util/binance_mig.py
  tests/conftest.py
  tests/persistence/test_migrations.py
  tests/persistence/test_persistence.py
  tests/plugins/test_pairlist.py
  tests/plugins/test_pairlocks.py
  tests/plugins/test_protections.py
  tests/rpc/test_rpc.py
  tests/rpc/test_rpc_apiserver.py
  tests/rpc/test_rpc_telegram.py
  tests/test_freqtradebot.py
  tests/test_integration.py
Labels: Tech maintenance

#8338 Fix exceptions when training fails
  freqtrade/freqai/freqai_interface.py
Labels: freqAI

#8343 Add pair output to "tossed" messages
  freqtrade/freqai/data_kitchen.py
Labels: freqAI

#7951 strategy_updater
  docs/utils.md
  freqtrade/commands/__init__.py
  freqtrade/commands/arguments.py
  freqtrade/commands/strategy_utils_commands.py
  freqtrade/strategy/strategyupdater.py
  requirements.txt
  tests/commands/test_commands.py
  tests/test_strategy_updater.py
  user_data/strategies/.gitkeep
Labels: Enhancement

#8344 Fix db concurrent problem
  freqtrade/persistence/models.py
  freqtrade/rpc/api_server/deps.py
  freqtrade/rpc/telegram.py
  tests/rpc/test_rpc_telegram.py
Labels: Bug

#8360 Okx stoploss on exchange
  freqtrade/exchange/okx.py
  tests/exchange/test_exchange.py
  tests/exchange/test_okx.py
Labels: Enhancement

#8380 use github to download guess instead of gnu.org
  build_helpers/install_ta-lib.sh
Labels: Tech maintenance

#8364 Update freqai_interface.py
  docs/freqai-running.md
  freqtrade/freqai/freqai_interface.py
Labels: Bug, freqAI

#8379 Type sendmsg
  freqtrade/data/dataprovider.py
  freqtrade/freqtradebot.py
  freqtrade/rpc/api_server/webserver.py
  freqtrade/rpc/rpc.py
  freqtrade/rpc/rpc_manager.py
  freqtrade/rpc/rpc_types.py
  freqtrade/rpc/telegram.py
  freqtrade/rpc/webhook.py
  tests/test_freqtradebot.py
Labels: RPC, Tech maintenance

#8389 typo: above should be below
  docs/freqai-reinforcement-learning.md
Labels: Documentation, freqAI

#8361 featherdatahandler: implement trades_store/_trades_load
  freqtrade/constants.py
  freqtrade/data/history/featherdatahandler.py
  tests/data/test_datahandler.py
  tests/testdata/XRP_ETH-trades.feather
Labels: Enhancement

#8386 price to precision rounding
  freqtrade/exchange/__init__.py
  freqtrade/exchange/exchange.py
  freqtrade/exchange/exchange_utils.py
  freqtrade/exchange/kraken.py
  freqtrade/freqtradebot.py
  freqtrade/persistence/trade_model.py
  freqtrade/plugins/pairlist/PrecisionFilter.py
  tests/exchange/test_binance.py
  tests/exchange/test_exchange.py
  tests/exchange/test_huobi.py
  tests/exchange/test_kraken.py
  tests/exchange/test_kucoin.py
  tests/test_freqtradebot.py
Labels: Enhancement
