Repository freqtrade/freqtrade, pull requests merged in 2024-06, with the labels that each got.

#10235 Add Windows Setup Script and Pester Unit Tests for Freqtrade
  .github/workflows/ci.yml
  docs/windows_installation.md
  setup.ps1
  tests/setup.Tests.ps1
Labels: Enhancement, Install

#10307 Revert "Workaround macos CI fails"
  .github/workflows/ci.yml
Labels: Dependencies, Tech maintenance

#10315 Run CI against ubuntu 24.04
  .github/workflows/ci.yml
Labels: Tech maintenance

#10269 Add force_enter optional args and tests
  docs/rest-api.md
  ft_client/freqtrade_client/ft_client.py
  ft_client/freqtrade_client/ft_rest_client.py
  ft_client/test_client/test_rest_client.py
Labels: Enhancement, RPC
