Repository freqtrade/freqtrade, pull requests merged in 2024-12, with the labels that each got.

#10858 Improve binance historic OHLCV download speed
  docs/configuration.md
  freqtrade/data/history/history_utils.py
  freqtrade/exchange/binance.py
  freqtrade/exchange/binance_public_data.py
  freqtrade/exchange/exchange.py
  tests/data/test_history.py
  tests/exchange/test_binance.py
  tests/exchange/test_binance_public_data.py
  tests/exchange/test_exchange.py
  tests/testdata/binance/binance_public_data/futures-um-klines-BTCUSDT-1h-2024-10-28.zip
  tests/testdata/binance/binance_public_data/spot-klines-BTCUSDT-1h-2024-10-28.zip
Labels: Enhancement

#11000 Dry-run multi-wallet support
  build_helpers/schema.json
  docs/advanced-hyperopt.md
  docs/configuration.md
  freqtrade/commands/optimize_commands.py
  freqtrade/configuration/config_schema.py
  freqtrade/exchange/binance.py
  freqtrade/exchange/exchange.py
  freqtrade/exchange/kraken.py
  freqtrade/optimize/analysis/lookahead_helpers.py
  freqtrade/optimize/hyperopt/hyperopt_optimizer.py
  freqtrade/optimize/hyperopt_loss/hyperopt_loss_calmar.py
  freqtrade/optimize/hyperopt_loss/hyperopt_loss_interface.py
  freqtrade/optimize/hyperopt_loss/hyperopt_loss_max_drawdown_relative.py
  freqtrade/optimize/hyperopt_loss/hyperopt_loss_multi_metric.py
  freqtrade/optimize/hyperopt_loss/hyperopt_loss_profit_drawdown.py
  freqtrade/optimize/hyperopt_loss/hyperopt_loss_sharpe.py
  freqtrade/optimize/hyperopt_loss/hyperopt_loss_sortino.py
  freqtrade/optimize/optimize_reports/optimize_reports.py
  freqtrade/plot/plotting.py
  freqtrade/rpc/rpc.py
  freqtrade/util/__init__.py
  freqtrade/util/dry_run_wallet.py
  freqtrade/wallets.py
  tests/optimize/test_hyperoptloss.py
  tests/rpc/test_rpc.py
  tests/test_wallets.py
Labels: Enhancement, Non-spot

#11046 Fix orderflow cache
  freqtrade/data/converter/orderflow.py
  freqtrade/strategy/interface.py
  tests/data/test_converter_orderflow.py
Labels: Bug

#11087 Bump ccxt to 4.4.40
  requirements.txt
Labels: Dependencies, Python

#11086 add warning about loose logic
  docs/strategy-callbacks.md
Labels: Documentation

#11141 Adding drawdown information for hyperopt-list --export-csv command & small fix stake currency source
  freqtrade/optimize/hyperopt_tools.py
  tests/commands/test_commands.py
Labels: Enhancement, Hyperopt

#11143 Support Telegram group topics, add /tg_info command
  build_helpers/schema.json
  docs/telegram-usage.md
  freqtrade/configuration/config_schema.py
  freqtrade/rpc/telegram.py
  tests/conftest.py
  tests/rpc/test_rpc_telegram.py
Labels: Enhancement, RPC

#11144 Deprecate hdf5
  docs/data-download.md
  docs/deprecated.md
  freqtrade/data/history/datahandlers/idatahandler.py
  tests/data/test_datahandler.py
Labels: Tech maintenance

#11154 Zip backtest results
  freqtrade/commands/analyze_commands.py
  freqtrade/data/btanalysis.py
  freqtrade/data/entryexitanalysis.py
  freqtrade/misc.py
  freqtrade/optimize/backtest_caching.py
  freqtrade/optimize/optimize_reports/bt_storage.py
  freqtrade/rpc/api_server/api_backtest.py
  tests/data/test_btanalysis.py
  tests/optimize/test_backtesting.py
  tests/optimize/test_optimize_reports.py
Labels: Enhancement, Backtest

#11159 Add rich log handler
  freqtrade/commands/arguments.py
  freqtrade/configuration/configuration.py
  freqtrade/loggers/__init__.py
  freqtrade/loggers/ft_rich_handler.py
  freqtrade/optimize/hyperopt/hyperopt.py
  tests/test_log_setup.py
Labels: Enhancement

#11120 Add support for BNFCR
  build_helpers/schema.json
  docs/exchanges.md
  docs/leverage.md
  freqtrade/configuration/config_schema.py
  freqtrade/exchange/binance.py
  freqtrade/exchange/exchange.py
  freqtrade/exchange/exchange_types.py
  freqtrade/freqtradebot.py
  freqtrade/leverage/liquidation_price.py
  freqtrade/rpc/rpc.py
  freqtrade/wallets.py
  tests/exchange/test_exchange.py
  tests/freqtradebot/test_freqtradebot.py
  tests/rpc/test_rpc.py
Labels: Enhancement, Non-spot
