Repository freqtrade/freqtrade, pull requests merged in 2024-11, with the labels that each got.

#10857 Improved caching
  .github/workflows/ci.yml
Labels: Tech maintenance

#10782 Enable future positions to reverse their position
  docs/backtesting.md
  freqtrade/freqtradebot.py
  freqtrade/optimize/backtesting.py
  tests/freqtradebot/test_freqtradebot.py
  tests/optimize/test_backtest_detail.py
  tests/optimize/test_backtesting.py
Labels: Enhancement

#10901 Attempt Remove brew hdf5 installs
  .github/workflows/ci.yml
  docs/installation.md
Labels: Tech maintenance

#10902 feat: enhance data fetching logic with pagination to increase market …
  docs/includes/pairlists.md
  freqtrade/plugins/pairlist/MarketCapPairList.py
  tests/plugins/test_pairlist.py
Labels: Enhancement, Pairlist

#10919 Restore hyperopt logging, refactor hyperopt layout
  docs/hyperopt.md
  freqtrade/commands/hyperopt_commands.py
  freqtrade/optimize/hyperopt/__init__.py
  freqtrade/optimize/hyperopt/hyperopt.py
  freqtrade/optimize/hyperopt/hyperopt_auto.py
  freqtrade/optimize/hyperopt/hyperopt_interface.py
  freqtrade/optimize/hyperopt/hyperopt_logger.py
  freqtrade/optimize/hyperopt/hyperopt_optimizer.py
  freqtrade/optimize/hyperopt/hyperopt_output.py
  freqtrade/optimize/hyperopt_loss/hyperopt_loss_interface.py
  freqtrade/resolvers/hyperopt_resolver.py
  tests/optimize/test_hyperopt.py
Labels: Hyperopt

#10839 Hyperliquid
  README.md
  docs/exchanges.md
  docs/index.md
  docs/stoploss.md
  freqtrade/exchange/common.py
  freqtrade/exchange/hyperliquid.py
  requirements.txt
  tests/exchange/test_hyperliquid.py
  tests/exchange_online/conftest.py
  tests/exchange_online/test_ccxt_compat.py
Labels: Enhancement
