Repository freqtrade/freqtrade, pull requests merged in 2024-10, with the labels that each got.

#10735 Remove support for python 3.9
  .github/workflows/ci.yml
  README.md
  build_helpers/TA_Lib-0.4.32-cp39-cp39-linux_armv7l.whl
  build_helpers/TA_Lib-0.4.32-cp39-cp39-win_amd64.whl
  docs/index.md
  docs/installation.md
  docs/windows_installation.md
  freqtrade/__main__.py
  freqtrade/commands/strategy_utils_commands.py
  freqtrade/main.py
  freqtrade/rpc/api_server/web_ui.py
  ft_client/pyproject.toml
  pyproject.toml
  requirements-hyperopt.txt
  requirements.txt
  setup.ps1
  setup.sh
Labels: Tech maintenance

#10741 Improved liquidation price logic
  freqtrade/exchange/binance.py
  freqtrade/exchange/bybit.py
  freqtrade/exchange/exchange.py
  freqtrade/freqtradebot.py
  freqtrade/leverage/liquidation_price.py
  freqtrade/optimize/backtesting.py
  freqtrade/persistence/trade_model.py
  tests/exchange/test_binance.py
  tests/exchange/test_exchange.py
  tests/exchange_online/test_ccxt_compat.py
  tests/leverage/test_update_liquidation_price.py
Labels: Tech maintenance, Non-spot

#10746 Postpone imports on demand
  freqtrade/commands/analyze_commands.py
  freqtrade/commands/build_config_commands.py
  freqtrade/commands/data_commands.py
  freqtrade/commands/db_commands.py
  freqtrade/commands/deploy_commands.py
  freqtrade/commands/deploy_ui.py
  freqtrade/commands/hyperopt_commands.py
  freqtrade/commands/list_commands.py
  freqtrade/commands/optimize_commands.py
  freqtrade/commands/pairlist_commands.py
  freqtrade/commands/plot_commands.py
  freqtrade/commands/strategy_utils_commands.py
  freqtrade/configuration/__init__.py
  freqtrade/configuration/deploy_config.py
  freqtrade/main.py
  freqtrade/rpc/api_server/web_ui.py
  freqtrade/system/__init__.py
  freqtrade/system/asyncio_config.py
  freqtrade/system/gc_setup.py
  freqtrade/util/migrations/funding_rate_mig.py
  tests/commands/test_build_config.py
  tests/commands/test_commands.py
  tests/commands/test_startup_time.py
  tests/rpc/test_rpc_apiserver.py
  tests/test_main.py
Labels: Enhancement

#10773 fix: Support mps device where available
  freqtrade/freqai/base_models/BasePyTorchModel.py
Labels: freqAI

#10808 ci: update macos version to new images
  .github/workflows/ci.yml
Labels: Tech maintenance

#10805 Add new hyperopt loss function
  docs/hyperopt.md
  freqtrade/optimize/hyperopt_loss/hyperopt_loss_multi_metric.py
  tests/optimize/test_hyperoptloss.py
Labels: Enhancement, Hyperopt

#10779 Improve strategy development documentation
  docs/strategy-101.md
  docs/strategy-customization.md
  mkdocs.yml
Labels: Documentation

#10831 feat: auto-create logs dir if it's absent
  freqtrade/loggers/__init__.py
  tests/test_log_setup.py
Labels: Enhancement

#10827 fix: guarantee crash resiliency, as long as users reload bot gracefully
  build_helpers/schema.json
  docs/freqai-parameter-table.md
  freqtrade/configuration/config_schema.py
  freqtrade/freqai/freqai_interface.py
Labels: Bug, freqAI

#10856 Fix backtest parallelism with timeframe-detail
  freqtrade/optimize/backtesting.py
  freqtrade/persistence/trade_model.py
  tests/optimize/test_backtesting.py
  tests/persistence/test_persistence.py
Labels: Bug
