Repository freqtrade/freqtrade, pull requests merged in 2024-09, with the labels that each got.

#10485 Add exit signals to export in backtesting
  docs/advanced-backtesting.md
  freqtrade/data/entryexitanalysis.py
  freqtrade/optimize/backtesting.py
  freqtrade/optimize/optimize_reports/bt_storage.py
  freqtrade/optimize/optimize_reports/optimize_reports.py
  tests/data/test_entryexitanalysis.py
  tests/optimize/test_optimize_reports.py
Labels: Enhancement

#10639 Add entry-only and exit-only filters to --indicator-list in backtesting analysis
  docs/advanced-backtesting.md
  freqtrade/commands/arguments.py
  freqtrade/commands/cli_options.py
  freqtrade/configuration/configuration.py
  freqtrade/data/entryexitanalysis.py
  tests/data/test_entryexitanalysis.py
Labels: Enhancement

#10687 Initialize Trade objects with amount=0
  docs/trade-object.md
  freqtrade/freqtradebot.py
  freqtrade/optimize/backtesting.py
  freqtrade/persistence/trade_model.py
  freqtrade/wallets.py
  tests/freqtradebot/test_freqtradebot.py
  tests/rpc/test_rpc.py
  tests/test_wallets.py
Labels: Tech maintenance

#10711 fix: Update BasePyTorchRegressor.py
  freqtrade/freqai/base_models/BasePyTorchRegressor.py
  freqtrade/freqai/prediction_models/PyTorchTransformerRegressor.py
Labels: Bug, freqAI

#10671 Category for market cap pairlist
  docs/includes/pairlists.md
  freqtrade/plugins/pairlist/IPairList.py
  freqtrade/plugins/pairlist/MarketCapPairList.py
  tests/plugins/test_pairlist.py
Labels: Enhancement, Pairlist

#10723 Remove long deprecated protections from config setting
  build_helpers/schema.json
  docs/configuration.md
  docs/deprecated.md
  docs/developer.md
  docs/hyperopt.md
  docs/includes/protections.md
  freqtrade/configuration/config_schema.py
  freqtrade/configuration/config_validation.py
  freqtrade/configuration/deprecated_settings.py
  freqtrade/constants.py
  freqtrade/optimize/backtesting.py
  freqtrade/plugins/protectionmanager.py
  freqtrade/resolvers/strategy_resolver.py
  freqtrade/rpc/api_server/api_backtest.py
  tests/freqtradebot/test_freqtradebot.py
  tests/optimize/test_backtesting.py
  tests/plugins/test_protections.py
  tests/rpc/test_rpc_manager.py
  tests/strategy/strats/strategy_test_v3.py
  tests/test_configuration.py
Labels: Tech maintenance
