Repository freqtrade/freqtrade, pull requests merged in 2024-07, with the labels that each got.

#10352 Pairlist backtesting check
  freqtrade/optimize/backtesting.py
  freqtrade/plugins/pairlist/AgeFilter.py
  freqtrade/plugins/pairlist/FullTradesFilter.py
  freqtrade/plugins/pairlist/IPairList.py
  freqtrade/plugins/pairlist/MarketCapPairList.py
  freqtrade/plugins/pairlist/OffsetFilter.py
  freqtrade/plugins/pairlist/PerformanceFilter.py
  freqtrade/plugins/pairlist/PrecisionFilter.py
  freqtrade/plugins/pairlist/PriceFilter.py
  freqtrade/plugins/pairlist/ProducerPairList.py
  freqtrade/plugins/pairlist/RemotePairList.py
  freqtrade/plugins/pairlist/ShuffleFilter.py
  freqtrade/plugins/pairlist/SpreadFilter.py
  freqtrade/plugins/pairlist/StaticPairList.py
  freqtrade/plugins/pairlist/VolatilityFilter.py
  freqtrade/plugins/pairlist/VolumePairList.py
  freqtrade/plugins/pairlist/rangestabilityfilter.py
  freqtrade/plugins/pairlistmanager.py
  tests/optimize/test_backtesting.py
  tests/plugins/test_pairlist.py
Labels: Enhancement, Pairlist

#10273 ccxt.pro support - using websockets to get data
  docs/configuration.md
  freqtrade/constants.py
  freqtrade/exchange/binance.py
  freqtrade/exchange/bybit.py
  freqtrade/exchange/common.py
  freqtrade/exchange/exchange.py
  freqtrade/exchange/exchange_utils.py
  freqtrade/exchange/exchange_ws.py
  freqtrade/freqtradebot.py
  requirements-dev.txt
  tests/conftest.py
  tests/exchange/test_exchange_ws.py
  tests/exchange_online/conftest.py
  tests/exchange_online/test_ccxt_ws_compat.py
  tests/rpc/test_rpc_apiserver.py
Labels: Enhancement, WIP

#10405 Add rich table output
  freqtrade/commands/data_commands.py
  freqtrade/commands/hyperopt_commands.py
  freqtrade/commands/list_commands.py
  freqtrade/data/entryexitanalysis.py
  freqtrade/optimize/analysis/lookahead_helpers.py
  freqtrade/optimize/analysis/recursive_helpers.py
  freqtrade/optimize/hyperopt.py
  freqtrade/optimize/hyperopt_output.py
  freqtrade/optimize/hyperopt_tools.py
  freqtrade/util/__init__.py
  freqtrade/util/rich_progress.py
  freqtrade/util/rich_tables.py
  requirements.txt
  setup.py
  tests/commands/test_commands.py
  tests/conftest_hyperopt.py
  tests/data/test_entryexitanalysis.py
  tests/optimize/test_hyperopt.py
  tests/optimize/test_lookahead_analysis.py
  tests/optimize/test_recursive_analysis.py
Labels: Enhancement

#10417 Backtest tables -> Rich
  freqtrade/optimize/edge_cli.py
  freqtrade/optimize/optimize_reports/bt_output.py
  freqtrade/util/rich_tables.py
  tests/optimize/test_optimize_reports.py
Labels: Enhancement

#10420 Download Data - progressbar
  freqtrade/data/history/history_utils.py
  freqtrade/optimize/hyperopt.py
  freqtrade/util/__init__.py
  freqtrade/util/progress_tracker.py
  freqtrade/util/rich_progress.py
  tests/data/test_history.py
Labels: Enhancement

#10424 fix: remove contextmanager
  freqtrade/rpc/api_server/uvicorn_threaded.py
Labels: Tech maintenance

#10463 Add Config schema with description
  .github/workflows/ci.yml
  build_helpers/extract_config_json_schema.py
  build_helpers/schema.json
  freqtrade/configuration/config_schema.py
Labels: Enhancement, Tech maintenance

#10454 Add percent change pairlist
  build_helpers/schema.json
  docs/includes/pairlists.md
  freqtrade/constants.py
  freqtrade/exchange/exchange.py
  freqtrade/exchange/types.py
  freqtrade/plugins/pairlist/PercentChangePairList.py
  tests/conftest.py
  tests/plugins/test_percentchangepairlist.py
Labels: Enhancement, Pairlist
