Repository freqtrade/freqtrade, pull requests merged in 2024-03, with the labels that each got.

#9861 Add sorting to volatility and RangeStability pairlists
  docs/includes/pairlists.md
  freqtrade/plugins/pairlist/VolatilityFilter.py
  freqtrade/plugins/pairlist/rangestabilityfilter.py
  tests/conftest.py
  tests/plugins/test_pairlist.py
Labels: Enhancement, Pairlist

#9897 fix: try plotting as much info in xgboost tensorboard as possible
  freqtrade/freqai/prediction_models/XGBoostRegressor.py
  freqtrade/freqai/tensorboard/tensorboard.py
Labels: freqAI

#6908 Persistent storage of user-custom information
  docs/strategy-advanced.md
  docs/telegram-usage.md
  freqtrade/optimize/backtesting.py
  freqtrade/persistence/__init__.py
  freqtrade/persistence/custom_data.py
  freqtrade/persistence/models.py
  freqtrade/persistence/trade_model.py
  freqtrade/persistence/usedb_context.py
  freqtrade/rpc/rpc.py
  freqtrade/rpc/telegram.py
  tests/persistence/test_persistence.py
  tests/persistence/test_trade_custom_data.py
  tests/rpc/test_rpc_telegram.py
Labels: Enhancement

#9919 Bump catboost to 1.2.3
  requirements-freqai.txt
  tests/freqai/test_freqai_interface.py
Labels: Dependencies, Python

#9922 Ci - Run on native macos ARM runner
  .github/workflows/ci.yml
  tests/freqai/conftest.py
  tests/freqai/test_freqai_interface.py
Labels: Tech maintenance

#9923 Bump torch
  requirements-freqai-rl.txt
  tests/freqai/conftest.py
  tests/freqai/test_freqai_interface.py
Labels: Dependencies, Python

#9975 exception ConfigurationError
  docs/developer.md
  freqtrade/commands/analyze_commands.py
  freqtrade/commands/data_commands.py
  freqtrade/commands/deploy_commands.py
  freqtrade/commands/list_commands.py
  freqtrade/commands/optimize_commands.py
  freqtrade/commands/plot_commands.py
  freqtrade/commands/trade_commands.py
  freqtrade/configuration/config_validation.py
  freqtrade/configuration/deprecated_settings.py
  freqtrade/configuration/load_config.py
  freqtrade/configuration/timerange.py
  freqtrade/data/btanalysis.py
  freqtrade/exceptions.py
  freqtrade/exchange/exchange.py
  freqtrade/main.py
  freqtrade/rpc/api_server/api_backtest.py
  tests/commands/test_commands.py
  tests/exchange/test_exchange.py
  tests/test_main.py
Labels: Enhancement

#9955 Feature: trade lifecycle callbacks
  docs/bot-basics.md
  docs/strategy-callbacks.md
  freqtrade/freqtradebot.py
  freqtrade/optimize/backtesting.py
  freqtrade/strategy/interface.py
  freqtrade/templates/strategy_subtemplates/strategy_methods_advanced.j2
  tests/freqtradebot/test_freqtradebot.py
  tests/freqtradebot/test_stoploss_on_exchange.py
  tests/optimize/test_backtesting.py
Labels: Enhancement

#10015 Add freqtrade-clients as individually installable dependency
  .github/workflows/ci.yml
  build_helpers/freqtrade_client_version_align.py
  docs/rest-api.md
  ft_client/LICENSE
  ft_client/MANIFEST.in
  ft_client/README.md
  ft_client/freqtrade_client/__init__.py
  ft_client/freqtrade_client/ft_client.py
  ft_client/freqtrade_client/ft_rest_client.py
  ft_client/pyproject.toml
  ft_client/requirements.txt
  ft_client/test_client/__init__.py
  ft_client/test_client/test_rest_client.py
  scripts/rest_client.py
  setup.py
Labels: Enhancement

#10022 Align exitreasons, remove duplicated code
  freqtrade/optimize/optimize_reports/__init__.py
  freqtrade/optimize/optimize_reports/bt_output.py
  freqtrade/optimize/optimize_reports/optimize_reports.py
  tests/optimize/test_backtesting.py
  tests/optimize/test_optimize_reports.py
Labels: Backtest, Tech maintenance

#10023 Add lock post endpoint
  docs/rest-api.md
  freqtrade/rpc/api_server/api_schemas.py
  freqtrade/rpc/api_server/api_v1.py
  freqtrade/rpc/rpc.py
  ft_client/freqtrade_client/ft_rest_client.py
  ft_client/test_client/test_rest_client.py
  pyproject.toml
  tests/rpc/test_rpc.py
  tests/rpc/test_rpc_apiserver.py
Labels: Enhancement, RPC
