Repository freqtrade/freqtrade, pull requests merged in 2024-02, with the labels that each got.

#9750 Add tags per order
  docs/strategy-callbacks.md
  freqtrade/freqtradebot.py
  freqtrade/optimize/backtesting.py
  freqtrade/persistence/migrations.py
  freqtrade/persistence/trade_model.py
  freqtrade/rpc/api_server/api_schemas.py
  freqtrade/strategy/interface.py
  tests/optimize/test_backtesting.py
  tests/optimize/test_backtesting_adjust_position.py
  tests/rpc/test_rpc.py
  tests/test_freqtradebot.py
  tests/test_integration.py
Labels: Enhancement

#9267 Update stoploss order management
  freqtrade/freqtradebot.py
  freqtrade/persistence/migrations.py
  freqtrade/persistence/trade_model.py
  freqtrade/rpc/api_server/api_schemas.py
  freqtrade/rpc/rpc.py
  tests/conftest_trades.py
  tests/conftest_trades_usdt.py
  tests/persistence/test_migrations.py
  tests/persistence/test_persistence.py
  tests/persistence/test_trade_fromjson.py
  tests/rpc/test_rpc.py
  tests/rpc/test_rpc_apiserver.py
  tests/test_freqtradebot.py
  tests/test_integration.py
Labels: Enhancement

#9704 fix: logical error in the conditional checks for model classes
  freqtrade/freqai/utils.py
Labels: Bug, freqAI

#9821 improve volumepairlist "advanced filter mode" caching
  docs/includes/pairlists.md
  freqtrade/exchange/exchange.py
  freqtrade/plugins/pairlist/VolatilityFilter.py
  freqtrade/plugins/pairlist/VolumePairList.py
  freqtrade/plugins/pairlist/rangestabilityfilter.py
  tests/exchange/test_exchange.py
  tests/plugins/test_pairlist.py
Labels: Enhancement, Pairlist

#9847 Bump ccxt to 4.2.47
  freqtrade/exchange/common.py
  freqtrade/exchange/exchange.py
  freqtrade/exchange/exchange_utils.py
  requirements.txt
  setup.py
  tests/exchange/test_bybit.py
  tests/exchange/test_exchange.py
Labels: Dependencies, Python
