Repository freqtrade/freqtrade, pull requests merged in 2024-08, with the labels that each got.

#10482 chore: Remove pip pin from ci
  .github/workflows/ci.yml
  Dockerfile
  build_helpers/install_windows.ps1
  docker/Dockerfile.armhf
  setup.sh
Labels: Tech maintenance

#10400 Added unlock_at field for protection config
  .gitignore
  build_helpers/schema.json
  docs/includes/protections.md
  freqtrade/configuration/config_schema.py
  freqtrade/configuration/config_validation.py
  freqtrade/plugins/protections/cooldown_period.py
  freqtrade/plugins/protections/iprotection.py
  freqtrade/plugins/protections/low_profit_pairs.py
  freqtrade/plugins/protections/max_drawdown_protection.py
  freqtrade/plugins/protections/stoploss_guard.py
  tests/plugins/test_protections.py
  tests/test_configuration.py
Labels: Enhancement

#10529 add --trades to list-data command
  README.md
  docs/bot-usage.md
  docs/data-download.md
  freqtrade/commands/__init__.py
  freqtrade/commands/arguments.py
  freqtrade/commands/cli_options.py
  freqtrade/commands/data_commands.py
  freqtrade/data/history/datahandlers/idatahandler.py
  tests/commands/test_commands.py
  tests/data/test_datahandler.py
Labels: Enhancement

#10527 Backtesting - dynamic pairlist sorting
  docs/backtesting.md
  freqtrade/data/btanalysis.py
  freqtrade/optimize/backtesting.py
  tests/optimize/test_backtesting.py
Labels: Enhancement, Backtest

#10530 add price_precision_mode
  freqtrade/exchange/exchange.py
  freqtrade/freqtradebot.py
  freqtrade/optimize/backtesting.py
  freqtrade/persistence/migrations.py
  freqtrade/persistence/trade_model.py
  tests/conftest.py
  tests/exchange/test_exchange.py
  tests/persistence/test_persistence.py
  tests/rpc/test_rpc.py
  tests/strategy/test_interface.py
Labels: Enhancement

#10484 Move trades-refresh to async
  freqtrade/exchange/exchange.py
Labels: Enhancement

#10544 Improved imports for strategy
  docs/includes/strategy-imports.md
  docs/strategy-callbacks.md
  docs/strategy-customization.md
  freqtrade/strategy/__init__.py
  freqtrade/templates/base_strategy.py.j2
  freqtrade/templates/sample_strategy.py
  freqtrade/templates/strategy_subtemplates/buy_trend_full.j2
  freqtrade/templates/strategy_subtemplates/buy_trend_minimal.j2
  freqtrade/templates/strategy_subtemplates/indicators_full.j2
  freqtrade/templates/strategy_subtemplates/indicators_minimal.j2
  freqtrade/templates/strategy_subtemplates/plot_config_full.j2
  freqtrade/templates/strategy_subtemplates/sell_trend_full.j2
  freqtrade/templates/strategy_subtemplates/sell_trend_minimal.j2
  freqtrade/templates/strategy_subtemplates/strategy_attributes_full.j2
  freqtrade/templates/strategy_subtemplates/strategy_methods_advanced.j2
Labels: Enhancement
