Repository freqtrade/freqtrade, pull requests merged in 2025-02, with the labels that each got.

#11368 Allow NAN in Freqai datadrawer metadata
  freqtrade/freqai/data_drawer.py
Labels: freqAI

#11306 Add some distinction on the trailing_only_offset_is_reached
  docs/stoploss.md
Labels: Documentation

#11412 Add adjust_order_price callback
  docs/bot-basics.md
  docs/strategy-callbacks.md
  freqtrade/freqtradebot.py
  freqtrade/optimize/backtesting.py
  freqtrade/resolvers/strategy_resolver.py
  freqtrade/strategy/interface.py
  freqtrade/templates/strategy_subtemplates/strategy_methods_advanced.j2
  tests/freqtradebot/test_integration.py
  tests/optimize/__init__.py
  tests/optimize/test_backtest_detail.py
  tests/strategy/strats/broken_strats/broken_futures_strategies.py
  tests/strategy/test_strategy_loading.py
Labels: Enhancement
